### ISSUE TITLE
Self-hosted gitlab instance support

### ISSUE THREAD

**Issue by anragab** [fork-dev/Tracker#134]
Please add the ability to choose gitlab server url so that I can use my own gitlab instance

**Comment by DanPristupov** [comment]
Thank you for the request. I'll consider adding self-hosted gitlab support in one of the next releases (next month, probably).

**Comment by SilverDFlame** [comment]
I'd like to second this request, as the latest version, 1.0.60, does not have support for self-hosted gitlab instances.

**Comment by blatherus** [comment]
I'd also like to put in a vote for this - self-hosting is one of the main attractions of gitlab.

**Comment by 2called-chaos** [comment]
Duplicates #34

<sub>_This action was performed by a bored human that looks for a perfect git client. I'm trying to reference all duplicates to make life easier for the maintainers and to show that we really want this feature._</sub>

**Comment by danijelk** [comment]
@DanPristupov 
Hey Dan, now that it's released, how does one go about to tell the repo it's a gitlab remote? Does it guess it by the hostname? Can't seem to find a place to set this on 2.6.1

**Comment by DanPristupov** [comment]
Do you mean a private gitlab instance remote?

After you log in to an account, Fork will recognize the remote service using the server host.

For example if you log in to a custom GitLab instance 'https://git.server.org', a remote with url `https://git.server.org/user/testproject1.git` will be recognized as GitLab.

> Can't seem to find a place to set this on 2.6.1

Fork -> Accounts -> +

**Comment by danijelk** [comment]
> Do you mean a private gitlab instance remote?
> 
> After you log in to an account, Fork will recognize the remote service using the server host.
> 
> For example if you log in to a custom GitLab instance 'https://git.server.org', a remote with url `https://git.server.org/user/testproject1.git` will be recognized as GitLab.
> 
> > Can't seem to find a place to set this on 2.6.1
> 
> Fork -> Accounts -> +

Awesome work thanks for that, I was using git+ssh to access the remote which was the reason for it not working, I'm guessing this is purely https for now?

**Comment by DanPristupov** [comment]
@danijelk 

> I'm guessing this is purely https for now?

No. Most likely it's a bug. Please send the server address and the remote url (you can edit the private info) to my email (support@fork.dev) and will have a look what's going on.

**Comment by danijelk** [comment]
Dan found it out and will be patched in 2.6.4, I believe this issue can be closed.
