### ISSUE TITLE
prepare-commit-msg hook failure not always open "Git Error" window

### ISSUE THREAD

**Issue by flaviorighi** [fork-dev/Tracker#1530]
When prepare-commit-msg hook fails because the commit message template is not fullfilled correctly, the Git Error window is not opened most of the times.

In my hook I only check if the user replaces the commented lines.
Here is my hook:

```
if  grep -q '^#' $1 
then
    echo "error" 1>&2
    exit 1
fi
exit 0
```

I've tried without redirection to stderr, but the window is opened only sometimes.

**Comment by flaviorighi** [comment]
Closing because wrong issue tracker, I've seen this on Windows, I'll open in the right place

**Comment by DanPristupov** [comment]
I'll move it
