### ISSUE TITLE
When creating a branch with a `/` in the name, reveal the branch on the sidebar

### ISSUE THREAD

**Issue by Niels-NTG** [fork-dev/Tracker#165]
When creating a branch where the branch has a `/` in the name, Fork displays these inside folders. This is perfectly fine, but it would be nice if the appropriate folder expanded automatically to show you the branch you just created. Currently if you create a branch called `project/example2` I only see the folder `project`. I have to fold out the `project` folder manually to see my current branch `example2`.

**Comment by DanPristupov** [comment]
I could not implement that quickly. So, it will take some time to rework the sidebar inner structure to allow to open items automatically.

**Comment by ymm1x** [comment]
As tips, filtering the tree with '/' will expand child elements.

**Comment by petterikamppuririchie** [comment]
Voting to get this fixed :)
