### ISSUE TITLE
Branch filter blacklist

### ISSUE THREAD

**Issue by Turbo87** [fork-dev/Tracker#176]
I'm sometimes working in repositories where I would like to see all branches *except* one branch, for example `gh-pages`, which just adds unnecessary noise to the history graph. The current branch filter system only allows a whitelisting of branches, but it would be nice if a blacklist was also supported in some way.

**Comment by DanPristupov** [comment]
It seems to be trivial, but it's not :). There's no way to say git 'show commits for all branches excepting branchABC'. I probably will not have time to implement this feature in the near future and delay until more important tasks are done.

**Comment by DanPristupov** [comment]
We added the ability to hide particular branches (or folders) in Fork 2.6

**Comment by Turbo87** [comment]
sweeeeet! thank you :)
