### ISSUE TITLE
Starred section disappears when using the branch search filter

### ISSUE THREAD

**Issue by bdgeyter** [fork-dev/Tracker#204]
Steps: 
1) star a branch
2) filter the branch list by searching in the Filter field at the bottom of the list, making sure you don't match the starred branch

Expected: starred section is visible, just like all other empty or non-empty sections
Actual: starred section disappears when there are no results, as opposed to other sections which do show up when empty.

**Comment by DanPristupov** [comment]
Yes, this sounds inconsistent. I'l investigate this behavior.
