### ISSUE TITLE
Adding external tools - such as deltawalker

### ISSUE THREAD

**Issue by nbhanji** [fork-dev/Tracker#210]
Adding external tools support such as Deltawalker and others

**Comment by DanPristupov** [comment]
@nbhanji Fork already supports about 6 external diff/merge tools. What are the others tools you mentioned?

**Comment by nbhanji** [comment]
I thought I had mention Deltopia’s DeltaWalker.

Thanks.

**Comment by DanPristupov** [comment]
@nbhanji ok. I'll add it if other people vote for it.

**Comment by Macintron** [comment]
One of the reason why I didn't erase SourceTree from my disk is the missing "**BBEdit**" diff support.
See also #405.

**Comment by rburgst** [comment]
dont find deltawalker

**Comment by Triskae** [comment]
I vote for deltawalker !
