### ISSUE TITLE
Fork fails silently when staging changes in a locked repository

### ISSUE THREAD

**Issue by juraj-blahunka** [fork-dev/Tracker#212]
A git process hung in my git repository leaving a `.git/index.lock` file behind.
I was trying to stage my changes in Fork, but changes were'n moving out from staging area.
I found out about the left behind lock file after running `git add .` via CLI:
```
fatal: Unable to create '/path/to/repo/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

It would be helpful if Fork reported / proposed to remove the `index.lock` file instead of failing silently.

**Comment by DanPristupov** [comment]
@juraj-blahunka Hi. Yes, I confirm this bug. Will fix in the next update.
