### ISSUE TITLE
Filter commits by commit msg, username and date

### ISSUE THREAD

**Issue by clounie** [fork-dev/Tracker#215]
When you're trying to track down a certain commit, it can be really helpful to filter by message, username and date.

I realize the search box does commit message, but having a field for each would allow for much-needed precision when searching.

Column | Details
------------ | -------------
| Commit message | same functionality |
| Username | fuzzy search would be great |
| Date | Search by exact date, or by range of dates |

**Comment by DanPristupov** [comment]
Advanced search with complex queries is a must have. I'm going to implement it one day, just need to finish struggling with BitBucket/GHEnterprise/GLEnterprise first.

**Comment by clounie** [comment]
Thank you!
