### ISSUE TITLE
Alternating row background colours in list/table/tree views

### ISSUE THREAD

**Issue by Vusys** [fork-dev/Tracker#219]
Please add an option for alternating row background colours in list/ table/ tree views similar to Finder. 

If you have many short commit messages on a maximised window it can be quite difficult to line up the commit message to the author.

**Comment by DanPristupov** [comment]
Thank you. Added to my todo list.

**Comment by maksimovic** [comment]
Can it be an optional setting that can be toggled, please? I'm afraid that alternating rows would only bring noise in my case, and only degrade the experience which is otherwise very pleasant.
