### ISSUE TITLE
Non-modal history browsing

### ISSUE THREAD

**Issue by petterikamppuririchie** [fork-dev/Tracker#251]
Sourcetree does this right, IMO. I like to have multiple history browsing sessions/windows (for different files) open, and still be able to browse repository, commit etc. The main point here is that I want to be able to do everything I normally do with Fork even when I'm looking history.

**Comment by DanPristupov** [comment]
I figured out about this approach and I agree with you.
Currently user must open history again when he/she selected wrong commit. It's annoying. With non-modal window user will be able to keep both history and commit details open and switch between them.

Same can be applied to blame.
