### ISSUE TITLE
Wrong tag name when finish GitFlow release

### ISSUE THREAD

**Issue by kissferenc** [fork-dev/Tracker#259]
I created a new release with name: 'release/v.03-optional-pictures' (become name: release/release/v0.3-optional-pictures). After finish release this the tag name is: vrelease/v0.3-optional-pictures.

![screen shot 2018-04-07 at 15 59 33](https://user-images.githubusercontent.com/2789309/38455813-6e0d3206-3a7d-11e8-8ec5-47609304dd27.png)

This appears in version 1.0.65.1 but I think this problem don't appears by the previous version.

**Comment by DanPristupov** [comment]
That's strange. I'll try to update git-flow instance, we'll see if that helps.
