### ISSUE TITLE
one letter folder name cannot be deleted

### ISSUE THREAD

**Issue by matsui-goga** [fork-dev/Tracker#288]
On "create branch" or "rename branch",
you can delete any chars with ctrl-d
unless it is the only char of the folder name.

For example, "xy/foo" is the candidate branch name,
and hitting ctrl-d on the first 'x' is fine, results "y/foo".
But, ctrl-d on 'y' does not change the branch name.
Moreover, moving the cursor right after 'y' and hit backspace also does not delete it.
You have to delete '/' first.

I understand that a branch name should not start with '/',
but preventing deletion of the folder name seems strange.

**Comment by DanPristupov** [comment]
Yes, that's true. While it could be a bit confusing, I'm not sure how this can be handled in a better way.

P.S. In this way, I'd just select the wrong part and replace it starting typing.

**Comment by DanPristupov** [comment]
After 6 years it's fixed in 2.46 :)
