### ISSUE TITLE
Use other color to show diff in Diff View

### ISSUE THREAD

**Issue by Whirlwind** [fork-dev/Tracker#307]
In dark mode, the diff is red for delete lines and green for add lines, but I am a `red and green color blindness`. :(

**Comment by DanPristupov** [comment]
Can you provide any info how developers should solve such kind of problems?

**Comment by Whirlwind** [comment]
The `SourceTree`:
<img width="265" alt="image" src="https://user-images.githubusercontent.com/1251192/41242877-52baef3c-6dd3-11e8-8e3a-edb204b5254e.png">
First, there is a `+` and `-`, this is very clear.
Then the color is not red and green, and sourcetree app allow user custom the color.

**Comment by nebhale** [comment]
@DanPristupov I've not evaluated this directly, but the company I work for use [Color Oracle](http://colororacle.org) during design work to simulate these scenarios.

**Comment by DanPristupov** [comment]
@nebhale Sim Daltonism is a great application, thank you.

Here's how Fork looks. Seems to be confusing indeed.
<img width="594" alt="2018-06-11 at 20 24" src="https://user-images.githubusercontent.com/618115/41250009-f6cd31ac-6db5-11e8-9b48-053d41406bb9.png">

I'm not ready to change whole application palette, but I can introduce a color-blind mode with more distinctive highlighting colors and additional `-` `+` signs. Local/Remote branch colors could be improved too.

Few questions to @Whirlwind :
1. What about GitHub palette? It should be quite bad, right?
<img width="860" alt="2018-06-11 at 20 37" src="https://user-images.githubusercontent.com/618115/41250475-5590a902-6db7-11e8-9ab3-12b7b03ef435.png">

2. Do you use any special appearance settings in macOS?

**Comment by Whirlwind** [comment]
> What about GitHub palette? It should be quite bad, right?
There are multi way to make a difference in diff view in the Github:

1. different color in line number column , it is clear.
- different color for text background color, it is bad.
- Highlight for changed text, it is clear.
- `+` and `-` is very clear.

> Do you use any special appearance settings in macOS?

No, I just use the dark style in the Fork.

**Comment by Whirlwind** [comment]
By the way, the `color-blind` have multi type, not just `red and green`.

**Comment by luongvo209** [comment]
![image](https://user-images.githubusercontent.com/15828926/42622344-64913dae-85ea-11e8-8667-49c6b98678de.png)
My experiece in dark mode and when two changes sit next to each other is even much more challeging. I suggest that we 
1. if possible, enable side by side diff view
2. Change the color scheme of the diff, or let users change it, customize it the way they want.

**Comment by DanPristupov** [comment]
In 1.0.73 we used better colors in the dark theme.

**Comment by laurentvaills** [comment]
I can see this issue is closed but still with 2.0.4 the difference of colors is not good for colorblind people in the diff view (only when it switches to dark theme): 
![image](https://user-images.githubusercontent.com/724346/99991247-18014900-2db5-11eb-82fd-06f75a9ed7b6.png)

**Comment by apff** [comment]
Even in the dark theme it's still hard to distinguish the colors for some red-green colorblind users. 

An option to define custom highlight colors, like other users have suggested, would be really helpful and definitely solve this issue, not just for red-green but also for other types of colorblindness.

**Comment by DanPristupov** [comment]
In Fork 2.10 we added the option to show -+ marks near the change lines.

<img width="300" alt="Screenshot 2021-07-25 at 13 01 18" src="https://user-images.githubusercontent.com/618115/126896758-da7ec8d2-752b-44ad-ac92-7aac376fdbb1.png">

**Comment by laurentvaills** [comment]
Thanks for the -+ marks, that helps a bit. 
![image](https://user-images.githubusercontent.com/724346/126974671-9fb2d0ac-7f6f-438a-8d50-0a256ef9b71d.png)

By the way, you'll notice that the background of the preview is not the same as in a real window.

**Comment by laurentvaills** [comment]
Thanks for the -+ marks.

![image](https://user-images.githubusercontent.com/724346/126974927-fe59e212-c2a0-41ac-b33d-15635d580397.png)

By the way, I just noticed that the background of the preview is not the same as the background of a real window.
