### ISSUE TITLE
Startup is slow

### ISSUE THREAD

**Issue by ulope** [fork-dev/Tracker#314]
When using the `fork commit` CLI command it takes almost 5 seconds for the commit view to appear. 

Compared to for example `gitx` (which only takes ~0.5s) this feels extremely slow.

**Comment by DanPristupov** [comment]
Does this happen only when you start Fork using CLI? Is the usual start up slow too?

**Comment by ulope** [comment]
The speed is the same. The difference is that starting it from the GUI doesn't load a project right away which makes it appear to be faster.
