### ISSUE TITLE
Mark local branches that are merged to master differently

### ISSUE THREAD

**Issue by aziz** [fork-dev/Tracker#32]
In order to be able to find and remove merged local branches it would be great if we could filter them out or the app render them in the sidebar with a marker to distinguish them.

**Comment by DanPristupov** [comment]
Sorry Allen, I missed your question. Fork currently grays out commits which are not included into your current branch. So, if you check out the master branch, you'll see what branches are not merged in.

I'm not sure about similar approach in the branch list. Gray color is already used for filter, and adding one more color will be confusing.

**Comment by clounie** [comment]
Maybe a different icon to the left of the branch name?

If this was a thing, would definitely want to be able to select the current "parent" branch (it's not always going to be master for everyone)

**Comment by DanPristupov** [comment]
Since Fork 1.90 we mark local branches with deleted remote branches, which is enough I think.

<img width="234" alt="Screenshot 2020-02-11 at 16 02 26" src="https://user-images.githubusercontent.com/618115/74248464-e87ec580-4ce7-11ea-80f2-40884a0a1f86.png">
