### ISSUE TITLE
[feature request] add current branch to commit message

### ISSUE THREAD

**Issue by bwl21** [fork-dev/Tracker#328]
# Request

when working with feature branches, It would be nice if the branchname (maybe even strip "/feature" to the commit message.

Of course it can be done manually but it would be more convenient, if it was done automatically or at least with click on a button similar to "amend"

**Comment by DanPristupov** [comment]
Prepare-commit-msg hook can be used for that: https://github.com/fork-dev/Tracker/issues/1371#issuecomment-848650440
