### ISSUE TITLE
[Feature request] Using github access token or oauth

### ISSUE THREAD

**Issue by imyzf** [fork-dev/Tracker#330]
It would be safer to access github using [token](https://github.com/settings/tokens) or oauth, rather than password.

**Comment by DanPristupov** [comment]
Fork does use oauth.

**Comment by imyzf** [comment]
Thanks for your reply. But I was asked to input username and password in Fork,

![image](https://user-images.githubusercontent.com/8298849/42485348-ddc9c334-8429-11e8-843a-9daa5a6357ff.png)

not like this in Sourcetree, inputing in the Github's webpage:

![image](https://user-images.githubusercontent.com/8298849/42485360-e9549972-8429-11e8-9b48-9b3b28ad7f5f.png)

**Comment by maksimovic** [comment]
+1 I'd prefer this way, too.

**Comment by mdeeter** [comment]
+1
