### ISSUE TITLE
Support for locally hosted gitlab server

### ISSUE THREAD

**Issue by mrvkino** [fork-dev/Tracker#34]
It would be nice to have support for a locally hosted gitlab server account (like for the official gitlab.com).

**Comment by DanPristupov** [comment]
I'm going to redesign the hosting accounts subsystem soon. Then I'll add support for all the missing hosting providers (including private instances)

**Comment by whkoh** [comment]
Hello Dan, has there been any updates on this? Does the current version (1.0.69.4) only support public Gitlab and Github? thanks

**Comment by jbergstroem** [comment]
This would be an excellent quality of life for me.

**Comment by lxnk** [comment]
DITO. Our physics department starts the gitlab server, so a number of people would love to use Fork here!

**Comment by persimmonsoft** [comment]
Me too. I would particularly like to have support for Pull Request creation for our self-hosted BitBucket server

**Comment by lucianf** [comment]
+1, gitlab ce is quite popular and it's a shame Fork only works with gitlab.com.
Although as per https://github.com/ForkIssues/Tracker/issues/796#issuecomment-551100473_ it sounds like there's no plan for the hosting providers redesign.

**Comment by svoop** [comment]
+1 as well. I have a few public repos on gitlab.com and tons of private ones on my own instance. Would be awesome to have direct access to both. (As well as non-personal repos on any provider, see #431)

**Comment by svoop** [comment]
@DanPristupov Missed the roll out of this one: very cool and works like a charm, big thanks!
