### ISSUE TITLE
Can't use Fork without specifying git config email

### ISSUE THREAD

**Issue by adamalton** [fork-dev/Tracker#377]
I've just installed version 1.0.69.4, and now at startup I get this screen:

<img width="671" alt="screen shot 2018-08-08 at 20 10 19" src="https://user-images.githubusercontent.com/270255/43858888-1ad5e8a0-9b47-11e8-8b7f-16902774ac6e.png">

It forces me to either specify an email address, or cancel (which quits the app).  This is annoying because I very deliberately don't have an email address set in my global git config.

The reason for not setting `user.email` in the global git config is that I commit using several different identities depending on what I'm working on.  E.g. in personal projects I'll commit as `me@gmail.com`, in projects for my employer I'll commit as `me@my-employer.com`, and for some _client_ projects for my employer I'll commit as `me@client-company.com`.

Git allows you to set `user.email` to be different per repo, and if you leave you global `user.email` empty then each time you commit to a _new_ repository it will prompt you to set your email address.  This avoids accidentally committing to a personal project with my company email or vice versa.  So I very deliberately don't want to set the global `user.email` setting.

Fork is now forcing me to either set that global setting or not use it.  This is quite a significant blocker.

**Comment by nebhale** [comment]
Huh, I regularly have to rewrite history because I forget to override the global email in a newly cloned repository.  This is a great strategy to prevent this, and I'd love it if Fork supported it.

**Comment by vleeuwenmenno** [comment]
How is this still an open issue? Has there been any changes or updates to this?

**Comment by DanPristupov** [comment]
I think now Fork allows empty `user.name` and `user.email` fields
