### ISSUE TITLE
Allow signed commits without requiring GPGtools package

### ISSUE THREAD

**Issue by tonyarnold** [fork-dev/Tracker#378]
I currently have my git commits signing using command line GPG tooling - it would be nice to continue to be able to use that, without having to install the UI applications.

**Comment by svoop** [comment]
Same here: I've installed GPG via Homebrew, it would be nice if Fork recognized this as well. Homebrew installes the GPG binary here: `/usr/local/bin/gpg`.

@DanPristupov Are there any other dependencies for the GPG integration to work but the GPG binary?

(OT: I've just added my first custom command, what a fracking awesome killer feature, great job!)

**Comment by DanPristupov** [comment]
@svoop fork uses `/usr/local/MacGPG2/bin/gpg2` and performs the following 2 commands:

* `/usr/local/MacGPG2/bin/gpg2 --list-secret-keys --with-colons` (to get the available keys)
* `/usr/local/MacGPG2/bin/gpg2 --batch --no-tty "$@"` during commit

Can you check if `/usr/local/bin/gpg` in your case handles `--list-secret-keys --with-colons` properly?

**Comment by svoop** [comment]
Homebrew currently installs GPGv2 as `/usr/local/bin/gpg` (not as `gpg2`):

```
$ gpg --version
gpg (GnuPG) 2.2.17
```

The binary from MacGPG is version 2.2.10, however, the two commands you listed use arguments which AFAIS haven't changed and both work. (Tried the first one: okay. For the second one, I don't know what `$@` is inserted, but `--batch --no-tty` certainly works.)

**Comment by svoop** [comment]
@DanPristupov By the way, MacGPG appears to install the following symlink:

```
lrwxr-xr-x  1 root  wheel  27 Nov 16  2012 /usr/local/bin/gpg -> /usr/local/MacGPG2/bin/gpg2
```

Therefore, I guess it should be okay if you just depend on `/usr/local/bin/gpg` to support both. And if you want to enforce a certain minimal version of GPG, just ask the binary with `gpg --version`.

**Comment by DanPristupov** [comment]
OK, I'll try.

A note for myself: https://github.com/ForkIssues/Tracker/issues/258

**Comment by DanPristupov** [comment]
Surprisingly I cannot make it work. I deinstalled gpg tools, then installed GnuPG `brew install gpg`.

```
$ gpg --version
...
gpg (GnuPG) 2.2.17
libgcrypt 1.8.5
...
```

It returns the keys correctly (`gpg --list-secret-keys`) but fails to sign a commit:


```
$ git -c gpg.program=/usr/local/bin/gpg commit -m "test" -S --gpg-sign=A95BB9284D5BD3A1
error: gpg failed to sign the data
fatal: failed to write commit object
```

Do you have an idea what could be wrong?

Update (more info):

```
$ brew install pinentry-mac
Warning: pinentry-mac 0.9.4 is already installed and up-to-date
```

```
$ cat ~/.gnupg/gpg-agent.conf

default-cache-ttl 600
max-cache-ttl 7200
pinentry-program /usr/local/bin/pinentry-mac
```

**Comment by svoop** [comment]
@DanPristupov I have this one in my gpg-agent.conf as well: `use-standard-socket`. However, I'll experiment with my setup this afternoon and post the results here.

**Comment by DanPristupov** [comment]
Adding `use-standard-socket` doesn't make a difference.

**Comment by svoop** [comment]
@DanPristupov It works on my machine with the same versions of "gpg", "libgcrypt" and "pinentry-mac" installed. However, I have also "pinentry" installed (via Homebrew):

```
git -c gpg.program=/usr/local/bin/gpg commit -m "test" --gpg-sign=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[master (root-commit) b2f17bb] test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 foo.txt
```

Le's see...

* Do you get the window to enter the passphrase displayed at all?
* Have you `killall gpg-agent` after adding `use-standard-socket` to it's config?
* Is the pinentry-mac binary really there and executable?

My guess is gpg-agent. Here's how it's up on my box:

```
ps ax | grep gpg-agent
 1220   ??  Ss     0:03.47 gpg-agent --homedir /Users/xxx/.gnupg --use-standard-socket --daemon
```

By the way: My recipe to get GPG from Homebrew up and running is very simple and worked across the last two or three MacOS major version installs (which I always do from scratch):

```
brew install gnupg pinentry-mac
gpg --list-keys
pico ~/.gnupg/gpg-agent.conf
  pinentry-program /usr/local/bin/pinentry-mac
  use-standard-socket
  default-cache-ttl 120
  max-cache-ttl 1440
```

**Comment by DanPristupov** [comment]
> Have you killall gpg-agent after adding use-standard-socket to it's config?

Surprisingly, this solved the issue. The passphrase prompt window has appeared.

I'm testing if everything works as expected.

**Comment by mdogan** [comment]
`gpg-agent` [documentation says](https://www.gnupg.org/documentation/manuals/gnupg/Agent-Options.html) that `use-standard-socket` has no effect anymore since 2.1.

```
--use-standard-socket
--no-use-standard-socket
--use-standard-socket-p
Since GnuPG 2.1 the standard socket is always used. These options have no more effect. The command gpg-agent --use-standard-socket-p will thus always return success.
```

And running `gpg-agent --version` when `use-standard-socket` is added to the conf file says the same:

```
gpg-agent[53438]: /Users/xyz/.gnupg/gpg-agent.conf:1: obsolete option "use-standard-socket" - it has no effect
gpg-agent (GnuPG) 2.2.17
libgcrypt 1.8.5
...
```

**Comment by DanPristupov** [comment]
Alright, it works. The changes will be available in the 1.0.85 update.

Thank you to everyone!

**Comment by svoop** [comment]
Cool, thanks a bunch, @DanPristupov

**Comment by DanPristupov** [comment]
1.0.85 is out. Please check for updates and give me some feedback.

**Comment by svoop** [comment]
@DanPristupov Works like a charm on my Mac, awesome! 🥇

**Comment by svoop** [comment]
@DanPristupov 

The GPG keys dropdown in Fork lists revoked secret keys as well which will call signing to fail if chosen accidentally. Fortunately, it's very easy to remove them from the dropdown.

You're using `gpg --list-secret-keys --with-colons` to fetch a list with all objects and then ignore all lines but those beginning with `sec` (secret keys). Here's an example of the remaining lines:

```
sec:r:1024:17:B5XXXXXXXXXXXXXX:1000541173:1292274649::u:::sc:::+:::::0:
sec:r:1024:17:3CXXXXXXXXXXXXXX:1030341289:1292274863::u:::sc:::+:::::0:
sec:u:4096:1:2BXXXXXXXXXXXXXX:1241211635:::u:::scESC:::+:::23::0:
sec:u:4096:1:8CXXXXXXXXXXXXXX:1161246585:::u:::scESC:::+:::23::0:
```

The second column (one letter) contains the trust value. You want to make sure to **IGNORE** all lines which contain any of the following letters:

```
i -> The key is invalid (e.g. due to a missing self-signature)
d -> The key has been disabled
r -> The key has been revoked
e -> The key has expired
n -> The key is not valid
```

In the above example, the first two secret keys are "r" (revoked) and should be ignored, the latter two are "u" (ultimately trusted) and should be included in the dropdown.

See the [gpg details doc / field 2](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob_plain;f=doc/DETAILS) for a list with all trust value letters and their explanation.

**Comment by tonyarnold** [comment]
Could you consider letting us select the GPG tools we want to use? Later versions of Homebrew are installed into `/opt/homebrew`, not `/usr/local` (all M1 Macs would have their Homebrew installations in the new location).

**Comment by aonez** [comment]
Any workaround for this issue? The #258 workaround of manually installing GPG Tools does not work in Ventura at least, using Fork 2.27. I would prefer not to install more packaged than needed.

```sh
aone@aONe-Pro ~ % which gpg                                                   
/usr/local/bin/gpg
aone@aONe-Pro ~ % which gpg2
/usr/local/MacGPG2/bin/gpg2
```

<img width="500" alt="Screenshot 2023-03-25 at 13 34 14" src="https://user-images.githubusercontent.com/480163/227717559-cb2430cf-e75c-4971-9eea-175ee5b98c37.png">

**Comment by svoop** [comment]
@aonez What exactly is your goal, how do you want to install the required binaries other than with Homebrew?

**Comment by aonez** [comment]
Ops I misunderstood the issue title. I wanted to use GPG Tools (installed via Homebrew) as in #258, but Fork asks me to install `gnupg` and `pinentry-mac`.

It's odd because on another machine running Monterey and brewed GPG Tools this works as expected in Fork.

**Comment by DanPristupov** [comment]
@svoop since we are here, in Fork 2.27 untrusted keys are ignored, as you asked https://github.com/fork-dev/Tracker/issues/378#issuecomment-545623865

@aonez Try Fork 2.27.1 (https://cdn.fork.dev/mac/Fork-2.27.1.dmg). The issue with GPG Tools on M1 must be fixed there.

**Comment by aonez** [comment]
Fixed indeed @DanPristupov, thanks! Tried the develop update channel before posting but I suppose this build is not yet there, freshly cooked stuff 😄

**Comment by svoop** [comment]
@aonez I don't remember anymore whether pinentry-mac once was part of GnuPG itself or at least bundled in the same Homebrew formula. Either way, on older macOS, pinentry-mac may be installed implicitly. On Ventura those are two formulae for sure.

**Comment by svoop** [comment]
@DanPristupov 

> since we are here, in Fork 2.27 untrusted keys are ignored, as you asked https://github.com/fork-dev/Tracker/issues/378#issuecomment-545623865

Great news! One less thing to get a bloody nose from. 👍 Thanks a bunch!

**Comment by aonez** [comment]
Sorry for the noise mixed #1476 and this issue.

**Comment by DanPristupov** [comment]
OK, I think we can close this issue. Thank you to everyone 👍
