### ISSUE TITLE
Allow starring and filtering for branch folders

### ISSUE THREAD

**Issue by odrotbohm** [fork-dev/Tracker#382]
If you create branches with slashes in their names, you implicitly create a branch folder that can be collapsed in the branch view. It would be cool if those could be starred and also selected as filter. Starring would bring up the entire folder to the Starred section. Activating the filter would act as if all of the branches were activated manually.

**Comment by DanPristupov** [comment]
Hi. In Fork 2.6 you can set filter on folders or remotes.
