### ISSUE TITLE
SSH password form and dark mode

### ISSUE THREAD

**Issue by rbukovansky** [fork-dev/Tracker#385]
When Fork asks for the password to my SSH key, that form looks weird in dark mode.

![screen shot 2018-08-16 at 09 00 13](https://user-images.githubusercontent.com/1004491/44193434-2589ec00-a133-11e8-9bc6-d3c4ffbc676e.png)

**Comment by DanPristupov** [comment]
Somehow, I've never noticed that issue :). I believe it's not actual now.
