### ISSUE TITLE
[feature request] Add options for recursive fetch/push

### ISSUE THREAD

**Issue by noheger** [fork-dev/Tracker#387]
Please add options to the Fetch and Push dialogs allowing us to perform the following recursive fetch/push operations:

```
fetch --recurse-submodules
push --recurse-submodules=on-demand
push --recurse-submodules=check
```

Without a recursive push it can easily happen that you forget to push submodule changes that are referenced from the main repository, leaving the remote repository in an inconsistent state (referencing commits that don’t yet exist on the remote).

**Comment by Tricertops** [comment]
When working with submodules, this is a must-have feature. I would also like to see an indication in sidebar for submodules that needs push/pull.
