### ISSUE TITLE
[FeatReq] Log in to self-hosted GitLab

### ISSUE THREAD

**Issue by rbukovansky** [fork-dev/Tracker#389]
Could you please expand GitLab login form with a possibility to log in to self-hosted GitLab CE instance? Thanks.

**Comment by 2called-chaos** [comment]
Duplicates #34

<sub>_This action was performed by a bored human that looks for a perfect git client. I'm trying to reference all duplicates to make life easier for the maintainers and to show that we really want this feature._</sub>

**Comment by DanPristupov** [comment]
The biggest problem is that I don't have an access to such a repository and I don't have a time to to buy a server in a cloud, configure it and setup a GitLab instance..

**Comment by 2called-chaos** [comment]
@DanPristupov What do you need? I don't know how rich your current implementation is (aka. which endpoints you use) but you _could_ use [our gitlab-ce](https://git.bmonkeys.net) instance. When logged in I can get a list of my projects with `/api/v4/projects` and I guess you just pass an auth token for automation. I figure this should be very similar as to how gitlab.com works?

**Comment by DanPristupov** [comment]
@2called-chaos awesome! I just registered. Will try to use it and give you the feedback.

P.S. Here's what I need:
```
/user
/user/keys
/user/keys/\(id)
/user/keys
/projects
/projects/{dstWithNamespace}/merge_requests
```

**Comment by HansJK** [comment]
If privat hosting isn't supported, Fork just won't do it for me...

**Comment by zieglar** [comment]
any update？

**Comment by 2called-chaos** [comment]
> [New] Intergration with Bitbucket server, GitHub Enterprise and GitLab Server

Oh boy 😁

Unfortunately it appears to only list projects under the users namespace? None of our company projects (in group namespaces) show up. And in the clone dropdown window choosing Gitlab server doesn't show the project table at all like Github does.

Let me know if I should report them somewhere else :)

**Comment by DanPristupov** [comment]
@2called-chaos

> Unfortunately it appears to only list projects under the users namespace? None of our company projects (in group namespaces) show up.

Probably we must show all available repos when we the server GitLab. Could you try this build please? https://cdn.fork.dev/mac/Fork-2.6.1.dmg

**Comment by 2called-chaos** [comment]
> Probably we must show all available repos when we the server GitLab. Could you try this build please? https://cdn.fork.dev/mac/Fork-2.6.1.dmg

Yes this shows all the projects in the account section now. The other issue still persists though.
Thanks for fixing and integrating :)

For clarification this is GitHub vs GitLab in the clone modal.

![Monosnap 2021-03-30 23-50-48](https://user-images.githubusercontent.com/218011/113061714-c7f72080-91b2-11eb-8bd7-71d5d7b0e2f8.png)
![Monosnap 2021-03-30 23-51-40](https://user-images.githubusercontent.com/218011/113061778-e2c99500-91b2-11eb-96c6-dc9ccda190eb.png)

**Comment by 2called-chaos** [comment]
@DanPristupov I approved the account. I have to see if I can add you to some projects if you need that. I mean listing works in principle just that it doesn't appear when attempting to clone a new project. Our GitLab is up2date at v13.10.0

**Comment by DanPristupov** [comment]
@2called-chaos 

> The other issue still persists though.

Thank you for reminding me. I fixed it here. https://cdn.fork.dev/prerelease/Fork-2.6.6.dmg

> I approved the account. 

Thank you very much. I needed to ensure that two different accounts can work on same server. I will remove the second account soon.
