### ISSUE TITLE
Filter staged/unstaged files by name

### ISSUE THREAD

**Issue by clounie** [fork-dev/Tracker#39]
Hey Dan,

It'd be great to be able to filter files by name [primary sort] or partial match on the path [secondary sort] in the commit view.

Secondly but not worth a separate ticket...the search box in the top right of Fork could well be changed to read "Search Commits", making its purpose immediately clear.

**Comment by DanPristupov** [comment]
@clounie 
Hey. Sorry for the delay. It took me some time to figure out how this should be done globally.

I think sidebar also needs this feature.

May be a good solution could be to display a small filter text field below all long list views. Similar to XCode: 
<img width="1395" alt="2017-06-08 at 18 56" src="https://user-images.githubusercontent.com/618115/26940767-3fbaf09a-4c7c-11e7-83a0-92307a7409ed.png">

**Comment by clounie** [comment]
Same - must have missed this when I was checking ForkIssues. That sounds good.

**Comment by DanPristupov** [comment]
@clounie yeah, it's very easy to miss a message in GitHub issues. That's why I added GitHub notifications to Fork.

**Comment by clounie** [comment]
Nice. Will try that guy out...

**Comment by DanPristupov** [comment]
I started by adding the filter field for branches. I'm going to keep an eye on the usability and when it's good, I'll also add such filter to the commit view.

**Comment by clounie** [comment]
Awesome. Two thoughts:
1. Kinda wish it was between "Changes / All Commits" section and the branches section.
2. Introducing a (very) small wait time after the last key typed to filter might be nice. Just enough to keep the animation from jumping around.

**Comment by bdgeyter** [comment]
+1 on this. Should be on the Changes tab on a commit as well. Actually thought it was the diff-side-by-side icon, until I discovered that feature 😄. I'd prefer it going there actually, and the diff-side-by-side moving to the diff viewer somewhere.

**Comment by clounie** [comment]
Ref #84 - made a separate ticket for my first request there b/c I had forgotten this ticket existed.

**Comment by prime31** [comment]
+1 for a filter by file name. The only thing I open SourceTree for at this point is the ability to filter by filename. Would love to see it in Fork.

**Comment by frankrolf** [comment]
I had high hopes for Fork replacing SourceTree on my machine, but unfortunately the lack of this feature dampens the euphoria somewhat.
The nature of my work requires changing thousands of files, filtering before staging is absolutely essential.
Would love to see this! Thanks! :-)

**Comment by fbarthez** [comment]
Hey Dan, any progress on this? Fork is so much faster to use than SourceTree, but I really miss this one feature.

**Comment by DanPristupov** [comment]
@fbarthez not in the **near** future, but it's still on our todo list. I'd say, ETA ~6 months.

**Comment by clounie** [comment]
🙌 Thanks Dan!

**Comment by fbarthez** [comment]
Indeed, thanks from me as well!
