### ISSUE TITLE
need improved image diff view

### ISSUE THREAD

**Issue by bwl21** [fork-dev/Tracker#404]
Fork is currently displaying images side by side for diffing. For minor changes this is not really sufficient. So I ask for

1. support of pdf images
2. provide multiple options to show the diff
    - side by side (as now)
    - overlap and blink the different pixels
    - three images $local diff $ Remote
3. allow to zoom in to see more details

I know this is a difficult issue ...

**Comment by DanPristupov** [comment]
Image diff view improvement is in my todo list, but I don't have a time for that.

> 1. support of pdf images

I already have PDF+Sketch implemented in some stash. I'll have a look.

> 2. provide multiple options to show the diff

I agree, it would be nice to have overlap (with highlighting).

> 3. allow to zoom in to see more details

I'm pretty sure zoom will be pretty tricky to implement (mostly because there's a lot of work). However it can have just two modes: `fit to screen` and `real size`.

**Comment by bwl21** [comment]
thanks for your reply. I guess the two modes would be fine. I agree that arbitrary zoom might bei complicated. Maybe it is possible to add "double size".

I hacked a workaround using https://github.com/mapbox/pixelmatch

**Comment by lxnk** [comment]
I also join to this request.

I’m using mostly git for writing scientific papers using LaTeX. It works perfectly for TeX source (oh yeah, your diff visualisation and merging is good, love it!), but it was hard to work with figures till now. Your image diff visualisation is great, seriously! The only problem, the part of figures are in vector format, i.e. in PDF. Some are in AI (adobe illustrator, but this is same PDF, only different extension). Therefore, question:

If  the image diff implementation is a built-in feature, then can you add both PDF and AI (which is PDF but the file extension is different)?

Could you implement it through the .gitattributes to let git make the diffs itself? Here is a good example,  https://akikoskinen.info/image-diffs-with-git/

**Comment by ZevEisenberg** [comment]
+1 on PDF. Also, some PDF assets are white-on-clear, which would make diff pretty useless. I think Xcode does something clever where it detects if the asset has all white or clear pixels, and if so, they put a gray color behind it. Not sure how hard that would be, but it would certainly be a nice touch that really makes a difference for mobile development!

**Comment by jesusfj710** [comment]
Any update on this issue? In my project we work with a lot of images that are occasionally only a few pixels difference, sometimes comparing them in Fork's internal diff is impossible if we are talking about very landscape or portrait mode images on top of that.

**Comment by TanyaPristupova** [comment]
@jesusfj710 Fork shows image diff for images, but not for ones handled by LFS. You probably use LFS, right?

**Comment by bwl21** [comment]
@DanPristupov is it really completed? could you pls implement blinking, (switch between the imaged in 0.5Hz freuency)
