### ISSUE TITLE
[Feature Request] Recent vs All in Repository Manager Tab

### ISSUE THREAD

**Issue by drieran** [fork-dev/Tracker#413]
Hi,

I think that is more usable (for me) if in Repository Manager tab is, by default, "Recent" selected. Always I have to switch.

May be, if Recent is blank, then All should be selected.

Dani

**Comment by jackxujh** [comment]
Is there a way for me to help vote up this feature request? Really need this!

I have to say, that, showing _Recent_ has become a natural thing that you'd expect when you launch any app.

**Comment by DanPristupov** [comment]
This issue is still undone because I'm going to rework the Repository Manager completely soon. Then I'll add a way to see recent repos by default (may be introducing sort order could be a good solution).

**Comment by jackxujh** [comment]
Wow cool! Sounds like the new repository management workflow is a giant leap forward. Can't wait for the new Repository Manager to be put in use. 🤩

**Comment by hgustafsson** [comment]
I'm looking forward to the Repository Manager rework! Sorting sounds great.
An additional idea would be to remember which category was left open last time. 

Either way I hope it will be possible to have a new/custom category being opened by default 😊
