### ISSUE TITLE
Not all GitLab projects showing

### ISSUE THREAD

**Issue by corsa** [fork-dev/Tracker#431]
I have connected my GitLab account to Fork. When I try to clone a repository from GitLab, not all of my projects display in the Clone window. The only projects that show are my "Personal" projects, none of my projects that belong to groups that I created show up.

I'm using Fork 1.0.7.1.2 on macOS Mojave 10.14.

**Comment by wihodges** [comment]
+1 Yea I have same issue, would be great to have.

**Comment by luxlogica** [comment]
That is quite limiting, indeed  - all of the projects I use are in the company's group space (none in my personal space) so my list actually comes up empty.

**Comment by swilsondigital** [comment]
Wondering if there has been any update on this. Still having the same issue since all projects are in a company group space.

**Comment by ghost** [comment]
Guess it's related to this:

https://github.com/ForkIssues/Tracker/issues/347#issuecomment-405331065

**Comment by DanPristupov** [comment]
@gabriel-seoworks no, I fixed 347, but forgot to close.

**Comment by kdankert** [comment]
I would like to have this feature as well, as it would be way easier to clone repositories right through Fork instead of manually having to clone it using the url.

**Comment by svoop** [comment]
Same for GitHub, repos of organizations to which the user belongs are missing. I guess both on GitHub and GitLab, discovering these repos is more complicated and requires multiple API-lookups.
