### ISSUE TITLE
[Bug] The lines are wrapped in the changes view despite the «no wrap» setting

### ISSUE THREAD

**Issue by Finesse** [fork-dev/Tracker#433]
The «Word Wrap» setting is off but the code lines are wrapped:

![image](https://user-images.githubusercontent.com/9006227/46913551-6d61ae00-cfd2-11e8-90c8-62071cf4fc99.png)

Actually the «Word Wrap» setting makes an effect: the displayed lines are shorter.

I suppose this is an effect of the «Improve performance for minified files» improvement. I use the nowrap mode to compare the minified file size before and after the change. Hard wrapping the lines would be ok for me if I have another way to compare the size.

**Comment by DanPristupov** [comment]
I had to add a max limit, because the default textview control doesn't handle very wide lines good and can hang the application for up to 10 seconds for quite small files.

**Comment by Finesse** [comment]
Ok, it is not critical
