### ISSUE TITLE
[Dark mode] Allow selecting light/dark mode independently from system

### ISSUE THREAD

**Issue by elia** [fork-dev/Tracker#448]
Currently only dark mode can be forced when the system setting is light

**Comment by elia** [comment]
I used to have some apps that were light-mode and I think some apps allow to choose how they should appear. 

I've found [this workaround](https://www.tekrevue.com/tip/exclude-app-dark-mode-macos-mojave/) to keep some apps in light-mode when the system is in dark-mode.

So I thought could be a good addition to replace the `Always use dark theme` checkbox with a select that leaves more freedom to the user.

_feel free to close this issue right away, it's just a nice to have_

**Comment by rlabrecque** [comment]
Just to add, I use different styles for different types of tasks. Like personal -> dark, work -> light. Helps me organize way easier. (I'm on Windows so this doesn't effect me right now, but just wanted to add another perspective!)

**Comment by ssbarnea** [comment]
So true! While I use dark on the system I want to keep my git client non-dark. Not possible with current implementation. This needs to be a dropdown, with system pref default.

**Comment by simonlaustsen** [comment]
I would very much like to have this option as well – please add a selection so I can set the theme independently of the system ☝️
