### ISSUE TITLE
[Feature Request] Reintroduce coloured repository flags

### ISSUE THREAD

**Issue by AngryAnt** [fork-dev/Tracker#477]
I don't recall what they were named or how you configured them, but I was saddened when the little coloured flags got lost in the move to macOS native tabs. They were a really great and simple navigation aid in a busy window.

Could we perhaps get them re-introduced on the new native tabs?

![screen shot 2018-12-13 at 10 50 56](https://user-images.githubusercontent.com/102513/49930702-6caba200-fec5-11e8-91da-37d5d9c74afd.png)

**Comment by DanPristupov** [comment]
This might be possible in the Mojave, since they finally gave access to the tab view. I will have a look.

P.S. I really miss them too.
