### ISSUE TITLE
Custom push refspec is ignored when performing push

### ISSUE THREAD

**Issue by thdankert** [fork-dev/Tracker#478]
We're using a Gerrit-based development model and as such use their refspecs `refs/for/*` to push changes for review. This can be done either manually, by specifying the refspec for each `git push` command, or by setting a default [push refspec](https://git-scm.com/book/en/v2/Git-Internals-The-Refspec#_pushing_refspecs) in the project's `.git/config` file.

When setting it in the git config, it will automatically be used when performing `git push $remote $branch`, but starting with Fork 1.0.71 this setting is no longer respected, and changes end up in the tracking branch, instead of the one defined in the push refspec.

**Comment by DanPristupov** [comment]
Ouch. I didn't know such a problem could exist.

For now, I can publish old Fork version or you can create a reference custom action (please ask me if you need a help).

Regarding the fix/solution:

Will ability to push local branch to any remote branch help? Or you must push without specifying the destination branch?

So the Push dialog would have the following fields:
1. Local branch (target)
2. Remote server [combobox]
3. Remote branch [combobox, nullable?]

Is that OK?

**Comment by thdankert** [comment]
Hi Dan,

I can definitely use custom actions as a workaround (when I created this issue, I also noticed #123, where this was also discussed).

Regarding your proposed solution:
While it will help to specify the remote branch, it should probably not be a combo box.
The thing with gerrit is, that these "refs/for/..." refspecs are not real branches, but have a special meaning for the gerrit server. They won't appear in the list of branches, and can't be checked out directly.

I did not have a look at the actual git command being generated by pushing in Fork, but from the commandline I do it like this:

`git push origin master`

which will push to remote `origin`, refspec `/refs/for/master`.

According to the git documentation, git push will try to find the default refspec by consulting the `remote.*.push` configuration, which looks as follows for my project:
```
[remote "origin"]
	url = $real_world_project_url$
	fetch = +refs/heads/*:refs/remotes/origin/*
	push = refs/heads/*:refs/for/*
```

Maybe it's enough to implement the same behaviour in Fork, without adding more UI elements to the push dialog.

**Comment by DanPristupov** [comment]
I think I can recognize repositories with Gerrit by checking for having the `/refs/for/` refspec.
Do you think it's a good idea to implement a special Push dialog for Gerrit? That could  make everybody happy...

**Comment by thdankert** [comment]
This will most likely not work, because Gerrit does not expose these special refspecs (see https://stackoverflow.com/a/10461674).

I don't think a special "Push to Gerrit" dialog is neccessary.
I'd rather find the root cause, but I don't know how Fork handles pushes or creates the git command: can you check why the push refspec is ignored here?

**Comment by DanPristupov** [comment]
The problem should be fixed in 1.0.74. Can I close this issue?

**Comment by thdankert** [comment]
Hi Dan,

Thanks for fixing this - I did not try it out yet, but I will give you feedback in a bit!

**Comment by DanPristupov** [comment]
@thdankert thank you. I will have a look one more time.

**Comment by thdankert** [comment]
Right now I use the custom commands as a workaround:
I have a simple "Push for Review" command, that just issues "git push master origin" on the commandline.

**Comment by DanPristupov** [comment]
OK, I don't see how we can handle such cases without confusion for other users.

There are two options: 
- Gerrit users can create custom action
- I should add a dedicated "Push to Gerrit" dialog, it there is a demand.

**Comment by KPhi** [comment]
I'm also affected by this issue through using Gerrit. SourceTree handles this situation just fine, because the refspec is respected in the push dialog and it displays `refs/for/*` automatically. For "emergencies", the remote branch can also be manually overwritten, because the remote branch control is a combo-box.

In my opinion, the best way to resolve this issue is to respect the refspec definitions in the config, because any users in such a situation will have defined these themselves and will therefore also not be confused by the remote branch selection being different than usual.

**Comment by mike-lischke** [comment]
This is a pretty long standing issue and the number of complains shows there's demand to improve this part of Fork.

@DanPristupov Why is it not possible to use the `push` setting from .git/config, if given? If there's no such setting simply use what you do now. That should serve both worlds.

**Comment by DanPristupov** [comment]
You can see the exact git request in the activity manager on the toolbar. Currently Fork explicitly mentions the destination and git doesn't take the .git/config value into account.
Why does Fork explicitly mention the remote destination branch? Because that branch is selected in the push dialog.

This is a consequence of design decisions we made long time ago.

To solve this problem, we should probably add the `[default]` option to the destination dropdown in Push to allow to not define destination strictly.

**Comment by mike-lischke** [comment]
Yes, `[default]` is probably a good option. Should be explained well to users to avoid confusion. Does this use the tracked branch if no push refspec is given (provided there is one)? If so most people would never need to change this drop down.

That gives me an idea for a FR: allow to specify the push refspec in the remote creation dialog and write that value to .git/config.

**Comment by DanPristupov** [comment]
> Does this use the tracked branch if no push refspec is given (provided there is one)?

It should, but I need to test this.

> If so most people would never need to change this drop down.

Yes, exactly 👍

**Comment by DanPristupov** [comment]
We made some improvements in 1.0.99 and now custom refspec should be taken into account. Could you check this please?

**Comment by mike-lischke** [comment]
@DanPristupov Pushing with a custom refspec works for me now - great work! You can close this issue as far as I'm concerned.

**Comment by thdankert** [comment]
@DanPristupov I'm afraid we no longer use Gerrit and switched to Github last year, so I can't test this any longer.
Still, thanks for implementing this feature! 👍

**Comment by DanPristupov** [comment]
All right. Thank you to everyone! 👍
