### ISSUE TITLE
[Feature Request] Change line-height of commit tree

### ISSUE THREAD

**Issue by yannbolliger** [fork-dev/Tracker#481]
Really glad to have found this client. As a long-time Sourcetree user I had to find something with a similar UI but acceptable performance. This seems to be it.

However, it would be really nice to be able to customize the commit tree a bit:
 - increasing font-size
 - increasing line-height

Thanks for considering.

**Comment by yannbolliger** [comment]
This is possible. I never investigated into complaints on Sourcetree except the ones for lacking performance. The line-height is just a personal preference and therefore I suggested it as a configurable option.

**Comment by maksimovic** [comment]
While I prefer the most compact view possible, I'd also welcome an option to increase the font/line-height sometimes. Maybe something easy to perform without diving into the preferences pane, like browsers do: <kbd>Cmd</kbd>/<kbd>Ctrl</kbd> + <kbd>+</kbd> or <kbd>-</kbd>.

**Comment by yannbolliger** [comment]
That would be perfect!!

(I should maybe clarify that in my idea this only involved the tree view, not the rest of the UI... But I think you get it.)

**Comment by DanPristupov** [comment]
Would you like to see an alternative vertical layout instead? https://github.com/ForkIssues/TrackerWin/issues/55#issuecomment-448265651

**Comment by kristian-puccio** [comment]
I would love this feature to take the form of preferences. The same way you can change the font of the diff/code view.
Loving the app BTW nice work!
