### ISSUE TITLE
How to modify merge commit message?

### ISSUE THREAD

**Issue by zhanggang807** [fork-dev/Tracker#488]
the default merge commit log is "merge branch x into  y "
How to modify merge commit log ???

**Comment by DanPristupov** [comment]
There's no way to override the message globally. But you can try to use `amend` to edit the latest commit message.

**Comment by zhanggang807** [comment]
Can add a input field or a dialog after merge successfully to support this feature like origin 'git merge' command do?

**Comment by aloker** [comment]
We're missing this feature, too, to adhere to our company's commit message policy.

Amending is way too manual and does not even always work, e.g. when finishing a release with git flow + backmerge. 

I'd appreciate a template system with placeholders, e.g. 
`chore: merge branch {source} into {destination}`.

**Comment by zhanggang807** [comment]
> latest

Have a development plan about this feature???

**Comment by DanPristupov** [comment]
@zhanggang807 Choose 'no-commit' mode in the merge dialog:
<img width="520" alt="Screenshot 2021-04-08 at 09 12 00" src="https://user-images.githubusercontent.com/618115/113983704-861d4880-984a-11eb-8f5b-567032ed8238.png">
