### ISSUE TITLE
How to change line background color in diff view?

### ISSUE THREAD

**Issue by iambocai** [fork-dev/Tracker#490]
I'm a deutan, current diff background color is too similar to me, I'm not able to distinguish the two.

![image](https://user-images.githubusercontent.com/2259715/50500630-9bad4080-0a8d-11e9-8c9d-caea7ed5d2a6.png)

**Comment by iambocai** [comment]
related issue #307 ,  

As many as 8% of the male and 0.5% of the female population are affected with some type of color blindness, most often the red-green form.

here is some suggestion about color-blind friendly palette ：https://venngage.com/blog/color-blind-friendly-palette/

**Comment by DanPristupov** [comment]
I'll try to introduce a high-contrast color mode in the next update. It wasn't technically possible at the time https://github.com/ForkIssues/Tracker/issues/307 was reported, but since that I made the required internal changes.
