### ISSUE TITLE
Add a small "is dirty" link

### ISSUE THREAD

**Issue by DavidBabel** [fork-dev/Tracker#500]
It will be great if we had an explicit way to show if there are modification since the last commit, adding, for example, a line here : 
![image](https://user-images.githubusercontent.com/5599375/51103699-07104580-17e4-11e9-8499-c9395fd843c0.png)

Which on click may redirect to the "Changes" tab

**Comment by DanPristupov** [comment]
I think the 'Local Changes' section name shows number of uncommitted changes clearly.

<img width="278" alt="Screenshot 2023-06-21 at 14 22 21" src="https://github.com/fork-dev/Tracker/assets/618115/fb4f37a1-66eb-423c-906d-781795794fd6">
