### ISSUE TITLE
Tags repeated in commit list

### ISSUE THREAD

**Issue by kontinuity** [fork-dev/Tracker#545]
Fork: 1.0.74.2

![image](https://user-images.githubusercontent.com/148402/53281858-94d14000-3755-11e9-9c8f-d61af1a316a4.png)

Problem goes away if I hide tags. 

![image](https://user-images.githubusercontent.com/148402/53281873-b92d1c80-3755-11e9-92c3-a5c94862c166.png)

We have a lot of tags on the same commit for this repository.

![image](https://user-images.githubusercontent.com/148402/53281888-ed084200-3755-11e9-8a72-6ac6f2a97a59.png)

**Comment by tpunder** [comment]
This problem still exists in Fork version 2.4

**Comment by tpunder** [comment]
Here is an example repo that reproduces it: https://github.com/tpunder/fork-repeated-tag-bug

Just do a `git clone https://github.com/tpunder/fork-repeated-tag-bug.git` and then open up in Fork:

<img width="2290" alt="fork-repeated-tag-bug" src="https://user-images.githubusercontent.com/34375/110356331-fab45b80-7fee-11eb-92ac-8019c6c738af.png">

This is in Version 2.4:

<img width="250" alt="About" src="https://user-images.githubusercontent.com/34375/110356453-20d9fb80-7fef-11eb-8c2b-77359b05788c.png">
