### ISSUE TITLE
Commit message lost in amend mode when switching to the changes view

### ISSUE THREAD

**Issue by odrotbohm** [fork-dev/Tracker#548]
Steps to reproduce:

1. In the commit view, check "Amend" box and add files to the staging area and alter the commit message to a new text.
2. Switch to the changes view.
3. Switch to the commit view.
4. The previously entered commit message is gone and the original one of the commit to be amended is shown.

Expected behavior:

In 4. don't reset the commit message to the original one but keep the current draft around.

Currently using 1.0.74.2 but not sure it's tied to this one in particular.

**Comment by DanPristupov** [comment]
Thanks, I reproduced that.
I'm sure it was there since the very beginning.

**Comment by tylerbenson** [comment]
I just experienced this after writing a nice commit message.  I was sad when it disappeared.
Mac Version 1.0.88
