### ISSUE TITLE
Fork is too cheap

### ISSUE THREAD

**Issue by davedelong** [fork-dev/Tracker#562]
I do not understand how you are giving Fork away for free. An app this good should be like $50 for a license or something.

This is an issue. I feel bad using this app because it is free, and apps this good deserve to be paid for.

**Comment by ZevEisenberg** [comment]
+1 I and a bunch of my coworkers use it, and this is exactly the kind of development tool that a lot of development teams wouldn't think twice about paying good money for.

**Comment by DanPristupov** [comment]
Thank you!

To be honest, right now we absolutely don't have a time for that. There are many mind blowing features in our plans and we're fully concentrated on them.

I already mentioned some times that my wife and I are both programmers and besides Fork we have a normal job. We don't have much expenses and spend all our spare time developing Fork. That's why we can afford to keep Fork free.

We might make Fork paid in the future and $50 price seems to be fair. But we need to finish what we want first.

Thank you very much guys. Messages like yours keep us motivated.

**Comment by neonb** [comment]
> right now we absolutely don't have a time for that

Not even PayPal donations or such? :)

**Comment by jedidja** [comment]
Agreed; any way to donate or help out that doesn't involve much time on your part to setup (e.g. PayPal, https://www.buymeacoffee.com, e.g.) would certainly get used!

**Comment by roolo** [comment]
I have just one thing to ask. When you'll want money, no subscriptions pls 🥺

**Comment by signalwerk** [comment]
I would really encourage you to setup a donation-option. best would be a normal bank-account with an IBAN (International Bank Account Number). Then 100% of  the money lands in your pockets. As a community we could then proof you that it's worth for you developing and probably even keep it free because you can make enough money just with the donations alone.

**Comment by rmacfie** [comment]
https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/

Maybe something to look into? I just want to show my appreciation 👍

**Comment by tflo** [comment]
> I have just one thing to ask. When you'll want money, no subscriptions pls 🥺

Could not agree more. A subscription would put me off, instantly.

**Comment by wachilt** [comment]
Agreed. I'd happily purchase a license for Fork.

**Comment by gernotstarke** [comment]
I use Fork regularly - and would feel way better if I could donate or pay...

**Comment by eegiazarov** [comment]
Same here, come on, grow up already ;)

**Comment by alex-vas** [comment]
"Pay what you want" (just google it), could be a good option. It might work even better from commercial perspective than other methods of commercialisation. Especially given that the market (software developers) are quite spoiled with open source and other types of free software given to us by large and often evil corporations ;o)

**Comment by NanoSector** [comment]
At first I was a bit skeptical when I saw Fork was free, especially since it seems to compete with the likes of Tower which is quite expensive at 60 euros a year. I love the client however and I would be happy to purchase a license as well!

**Comment by tomchapin** [comment]
@DanPristupov  I love the fact that Fork is free, and I deeply admire the altruism, but surely you can understand how it might be suspicious if something is free and not also open source?

As they commonly say, "nothing in life is free", and, "if a product is free, then that means you are the product".

Would you be willing to explain why you are unwilling to open source it?

**Comment by DanPristupov** [comment]
@tomchapin

Discussing open source is an off-topic here (https://github.com/ForkIssues/Tracker/issues/79), so I'll answer very briefly.

> Would you be willing to explain why you are unwilling to open source it?

This will not allow us to make Fork paid later.

> surely you can understand how it might be suspicious if something is free and not also open source?

As I mentioned above:

> We might make Fork paid in the future and $50 price seems to be fair. But we need to finish what we want first.

**Comment by tflo** [comment]
> We might make Fork paid in the future and $50 price seems to be fair. But we need to finish what we want first.

So, the ~$50 are already fixed?

**Comment by ChrisThompsonTLDR** [comment]
Add me to the list of people that use Fork and would like to contribute.

Thank you so much for this amazing piece of software.

**Comment by KaKi87** [comment]
Hey there,

It would be obvious to me that a software that helps contributing to FOSS becomes FOSS.

At least, that's how I use Fork, and I believe that this is how most of Fork's users uses it.

However, I agree that the developers should accept donations.

If Fork becomes monetized and makes it unusable from the last free version, I would be forced to go back to GitHub Desktop or find something else, which would be very sad for me.

Thanks

**Comment by TanyaPristupova** [comment]
> If Fork becomes monetized and makes it unusable from the last free version, I would be forced to go back to GitHub Desktop or find something else

OK, I suppose, you should switch to GitHub Desktop right now then :)

**Comment by Stannieman** [comment]
> It would be obvious to me that a software that helps contributing to FOSS becomes FOSS.

That's kind of a strange mindset... If you drink coffee to help you contribute to FOSS, should the coffee be free? Should Apple/Dell/Lenovo/whoever give you a free PC just because it helpes you contribute to FOSS? Everything in the world should cost no more than $0.00 just because somewhere someone happens to be using it to contribute to FOSS?

In the end it's everyone's good right to ask whatever they want for whatever they make, and it's completely up to you if you're willing to buy it for that price. That's how the economy works. Unless you have "the only thing" that can save the world and you're asking trillions of dollars for it, but then there's a whole other level of ethics involved.

**Comment by KaKi87** [comment]
I talked about majority.
Yes, the major use of git is open source.
No, the major use of computers is not open source.
And capitalism is doing the exact opposite of saving the world.

**Comment by gernotstarke** [comment]
please don't compare the two friendly persons giving us Fork to "capitalism" in general.

Imho it's completely legitimate to form a business around software or services - where else shall developers live from, if not by making money out of software... 

Therefore - if good, usable and stable software costs money, that's perfectly ok.

btw - git, linux and other well-known open source systems are backed by VERY rich companies. Ubuntu is sponsored by a billionaire, Docker by investors, Kubernetes by Google etc. Rarely is good open-source done only in the spare time of volunteers.

**Comment by astrolemonade** [comment]
I would be happy to pay 50 $ for a perpetual license for Fork if Fork comes to GNU/Linux.

**Comment by DanPristupov** [comment]
Yesterday we've met with Sebastian Herrmann @herrherrmann (one of the first 10 Fork users BTW) and became almost speachless when received gifts from you guys.

Don't have words to express our feelings. Thank you very much! You are the best ❤️

<img src="https://user-images.githubusercontent.com/618115/65605316-2c776500-dfa9-11e9-8598-ba545497c87f.jpg" width="450" />

![IMG_3485](https://user-images.githubusercontent.com/618115/65605248-0d78d300-dfa9-11e9-9b4a-fd9e74954548.jpg)

**Comment by maksimovic** [comment]
Ha! Really nice.

Btw, who's into music? 🎹

**Comment by aniforprez** [comment]
Oh wow what an amazing gesture by Herr Herrmann! I guess he does speak for all of us when we say thank you for the amazing git client and hopefully we can monetarily support it too whenever you feel comfortable opening that up. A one-time $50-60 seems more than fair considering the value it brings

**Comment by remy-burney** [comment]
Fork looks very much like the GitKraken software, from a design and usability point of view (not sure who copied who)
At first it's free, you use it for a year, and then they just changed it to a paid subscription that I can't afford so I move on to another git tool.
I appreciate your honesty though as you are not hiding the fact you will eventually ask people to pay for it.
I understand free is too good to be true, but there is a fine line between free and asking people to pay $30 or even $50 per user/year like GitKraken did it just crossing the "screw you" line.

I think you can have smarter subscription, like based on the number of repo you have, or number of push/pull you do, or things that detects your usage of the tool like teamviewer does. Just have some mechanisms in place that are there to be fair to all types of developers.

In the meantime, thanks for the free tool.

**Comment by tflo** [comment]
> I think you can have smarter subscription, like based on the number of repo […]

I think, the traditional pricing model (one-time purchase + payed upgrade every couple of years) is the “smarter subscription”.

**Comment by aniforprez** [comment]
> I think you can have smarter subscription, like based on the number of repo you have, or number of push/pull you do, or things that detects your usage of the tool like teamviewer does. Just have some mechanisms in place that are there to be fair to all types of developers.

Anyone who implements weird pricing like this on desktop software by limiting actions and features is headed for disaster. I'd much rather be charged a subscription than this abomination. Sublime Text's model of one time payment for some period of updates and renewed subscriptions is far better but Sublime has burned me on their ridiculously slow update cycle and general disinterest in community driven features; hence moving to other better alternatives like VSCode for Sublime Text and Fork for Sublime Merge

**Comment by KaKi87** [comment]
> At first it's free, you use it for a year, and then they just changed it to a paid subscription that I can't afford so I move on to another git tool.

[GitKraken is available for free for students](https://education.github.com/pack/offers), and a lot of other good software too.

> free is too good to be true

It shouldn't.

> I think, the traditional pricing model (one-time purchase + payed upgrade every couple of years) is the “smarter subscription”.

The smartest subscription ever is cracking.

> Sublime Text's model of one time payment for some period of updates and renewed subscriptions is far better

From my perspective, Sublime Text is free.

> Sublime has burned me on their ridiculously slow update cycle and general disinterest in community driven features

What about plugins ?

> better alternatives like VSCode for Sublime Text

You can quote Atom too.

> Fork for Sublime Merge

Never heard of it, thank you for making me discover this one.

**Comment by aniforprez** [comment]
Ok this is the final comment I'll make because pretty sure this issue constantly being brought up is reducing the visibility of other important issues

GitKraken has a very fully featured free version. AFAIK the one deal breaker is that private repos are not supported in the free version. I'm not sure how they check it but that seems a bummer. Personally it's way too damn slow and hogs a lot of resources by virtue of being an electron app so I never got round to using it fully

I don't support cracking. Sublime Text and Merge are INCREDIBLY difficult to crack and at this point I wouldn't bother either cause they're essentially nagware

ST plugin development is increasingly being abandoned because the plugin devs are all moving over to VSCode and have no incentive to develop for Sublime. The plodding, absolutely nonsensical update cycle and the fact that their plugin APIs are so weak and gimped compared to VSCode means that a lot of really useful Code plugins have no parallel in ST. I tried to make the switch back once because ST is very performant and it's impossible to replicate my Code setup now

Atom has gotten better but I gave up on it a number of years ago because it was also a massive resource hog and very slow

Sublime Merge s my go-to for Linux since the wonderful Fork does not have a Linux client yet. It has far fewer features and is sorely lacking in a bunch of options but suffices. On my Mac and Windows, Fork is 100% my tool of choice

**Comment by DanPristupov** [comment]
I just want to say that I'm going to clean non-related comments in this topic in a few days.

**Comment by KaKi87** [comment]
> Sublime Text and Merge are INCREDIBLY difficult to crack
You don't need to crack free software.

**Comment by tflo** [comment]
> The smartest subscription ever is cracking.
> […]
> You don't need to crack free software.

What’s the deal with your obsession with cracking? Are you totally broke? What is wrong with paying independent developers or small companies for their work, especially if the program is good and you’re actually using it?

**Comment by aniforprez** [comment]
@DanPristupov I think this thread is getting WAY off topic about now. Better to lock it until there's updates about pricing and stuff

**Comment by jt3k** [comment]
one-time $50 sounds reasonable, but not one-time every month(!)

**Comment by DanPristupov** [comment]
Hi guys,

Recently we released Fork 1.0.86 which has an ability to buy a license (*Help -> Fork Activation*). 

As we discussed previously, the price is **$49**.

* It is a one-time purchase (not a subscription)
* The license includes both personal and commercial use
* It works on up to 3 machines (should be enough, I think)

**Comment by maksimovic** [comment]
Well played on all three bullet points, as well as the reasonable price tag and the discount for those who are roaming around Github issues :D

License being valid on 3 machines should cover most of the use-cases that I can think of. E.g. being a developer who has 3 platforms to work on: MacOS, Windows, Linux (although no Fork there yet), or having a laptop and a desktop computer, optionally dual-boot on one of them, or... whatever, all sounds good and reasonable - not that I expected something different from you ;)

**Comment by aniforprez** [comment]
Finally, I can use the client guilt-free. Excellent work! Will be buying myself a licence within the day

**Comment by KaKi87** [comment]
As a student, I can't afford it anymore, so I'll stay at the latest open source version.

**Comment by maksimovic** [comment]
Perhaps there can be a solution for students / non-profit orgs as well.

**Comment by ChrisThompsonTLDR** [comment]
Is this Mac only?  I can't seem to figure out how to get 1.0.85 on Windows.  I'm on version 1.41.1.0.

**Comment by maksimovic** [comment]
@ChrisThompsonTLDR Fork for Windows has different release cycle (not sharing any code either) and issues are tracked here:
https://github.com/ForkIssues/TrackerWin

**Comment by DanPristupov** [comment]
@ChrisThompsonTLDR Yes, it's Mac only for now. However the license code will **also** work on Windows, when we implement it. So, it's safe to buy it now.

**Comment by KaKi87** [comment]
> Perhaps there can be a solution for students / non-profit orgs as well.

Well, 2020 will be my last year of life as a student and I still won't be able to afford it after that so, it won't actually help very much.

Oh, actually you can consider that Apple users must be richer than Windows and Linux users so maybe you can continue to distribute Fork for Mac as premium and Fork for Windows and Linux as freeware for personal use and premium for professional use :)

**Comment by ChrisThompsonTLDR** [comment]
> @ChrisThompsonTLDR Yes, it's Mac only for now. However the license code will **also** work on Windows, when we implement it. So, it's safe to buy it now.

How do I purchase?  I would need to install Fork on a Mac and then purchase?  I didn't see a way to buy a license on your website.

**Comment by DanPristupov** [comment]
https://fork.dev/buy

**Comment by gbiellem** [comment]
Excellent.  This is great and I am very keen to pay so I can support Fork.  Regarding the 3 machine limit.  I already have Fork on multiple machines and VMs and I'd prefer to only manage one license.   It is too late to ask for an unlimited option or a greater machine count with a higher price?

**Comment by DanPristupov** [comment]
@gbiellem please contact me by email license@fork.dev

**Comment by jibsaram** [comment]
This is great! This might sound a bit weird to some, but the biggest point of worry I had about Fork and what was holding me back really fully adopting it was that it was fully free, that's just hard to sustain long-term. You guys need to be able to pay rent too. Seeing a paid option being added is great, I hope this will become fully visible on the website soon, too.

May I ask, are there any plans for features specific to the paid/unlocked version? Or is this is going to remain identical to the free version, with the only difference being that this will hopefully help you be able to keep doing what you do?

Thanks a bunch!

**Comment by DanPristupov** [comment]
@hellodeibu thank you very much :)

> is this is going to remain identical to the free version

Yes, we'd like to go this way, at least in the near future.

We are thinking about introducing a special version with Fork [stickers](https://github.com/ForkIssues/Tracker/issues/217), but I'm not sure about that yet (Tanya has signed a few hundreds of postcards and her hand hurts already 🙂)

**Comment by umverteiler** [comment]
Great - finally we can support you 🙏🏻

![image](https://user-images.githubusercontent.com/13586174/69549147-049c8180-0f99-11ea-9a1a-ccbdcf4aafdd.png)

**Comment by lxnk** [comment]
Thank you again for your work!

**Comment by jt3k** [comment]
Thanks again for your work!
But maybe there are discounts for people from countries where $ 49 is a quarter of the monthly salary?

**Comment by L11R** [comment]
@jt3k it has regional price:
![image](https://user-images.githubusercontent.com/5345489/69658782-e2d0f680-108d-11ea-96fc-a622d0f3ff6c.png)

**Comment by jt3k** [comment]
@L11R what about 1000roubles :) ?

**Comment by savely-krasovsky** [comment]
@jt3k it's already cheap. Programmers in Russia are getting quite good salary. Fork is not necessary tool, if you haven't money, use git cli or something else.

**Comment by DanPristupov** [comment]
Sorry, I'll clean the topic.
@L11R  Yes. I think it's not about salary, to be honest...

**Comment by AndersonDev** [comment]
Bought. Ty for fixing this 👍

**Comment by SnapJag** [comment]
Thanks for offering a way to contribute to your efforts, and it's great tool. For those that "can't afford it", for such a great tool and great support naturally needs to be rewarded or burn out occurs and then it disappears. It's now a sustainable effort. Fully worth it. Thanks. Purchased and happier to contribute.

**Comment by KaKi87** [comment]
There is no such thing as *"burn out"* when you work for yourself, your passion and the FOSS community. But I seem to be the only one here to understand what that is.

**Comment by jedidja** [comment]
> Agreed; any way to donate or help out that doesn't involve much time on your part to setup (e.g. PayPal, https://www.buymeacoffee.com, e.g.) would certainly get used!

Finally! :) I missed the notification.

![image](https://user-images.githubusercontent.com/484442/70929001-215c3000-2000-11ea-914b-0852660d52c7.png)

**Comment by decuser** [comment]
Activated. Thanks for making a great client.

**Comment by russbishop** [comment]
@DanPristupov Good work; I remember having this conversation with you on Twitter a few years ago. I'm glad to see a sustainable business model for you & Tanya. 

edit: I emailed you the details of my request

**Comment by svoop** [comment]
Activated as well, happy to support you guys!

**Comment by neonb** [comment]
I guess this issue can be closed now that Fork is exactly the right price (free or $49, depending on your mood ;), right? Time to let some other issue take the top spot in the tracker.

**Comment by Regan-Koopmans** [comment]
Fork is by far the best git client I have encountered. Please let me donate to this project.

**Comment by bhgsbatista** [comment]
I paid, this is an amazing piece of software, hope you guys keep making it faster and better!

**Comment by theofanis** [comment]
Activated, thank you for this awesome software, shows it's built from engineer artists! One of the most Inspiring stories I've seen out there!

Edit: I would also like a bit more room with number of devices there, not unlimited but maybe 5 would be a better option, but that's just me who's using this on at least 4 computers (windows and mac).

**Comment by DanPristupov** [comment]
@theofanis thank you for the purchase. Please contact me by email: license@fork.dev.

@bhgsbatista we will!

**Comment by MichalBryxi** [comment]
👋 Very happy user here. From the thread here it seems you are shifting towards paid model, which is great if that supports you & the future development.
Just my 2¢: If you'd publish a "buy me a coffee" link, you would see a lot of people jumping in and helping out. I actually had a hard time finding out this issue & the license mail, because there is IMO no link on your website. Just a vague statement in license page that one should buy it :)

**Comment by aonez** [comment]
Glad to finally been able to support the project with some cash! ❤️

**Comment by Haprog** [comment]
Would be nice to see [Linux support](https://github.com/ForkIssues/Tracker/issues/153) get some attention now since I switched to Linux before Fork became commercial. Sadly I need to use GitKraken as an alternative on Linux now, but would rather pay for Fork.

**Comment by sfunke** [comment]
Happy to support Indie developers and this great piece of software! ❤️  

![Bildschirmfoto 2020-04-17 um 09 38 16](https://user-images.githubusercontent.com/149676/79544420-4be1f680-808f-11ea-9892-a79c5c00a658.png)

Thanks for choosing this payment model 👍

**Comment by uvw** [comment]
Another happy customer here. Fantastic work, guys! ❤️ 

<img width="442" alt="Screen Shot 2020-05-01 at 2 24 31 PM" src="https://user-images.githubusercontent.com/1078682/80843001-fb52b900-8bb7-11ea-9a28-ea7f3d064176.png">

Thank you!

**Comment by adroste** [comment]
@DanPristupov 
I am still sceptic. I payed for too many software products that claimed a "one-time purchase" would be enough. 
Actually it was the same with my last git-client -> Tower.
I paid "one time", then they announced a new major version and invalidated all old licenses and after that they did the same again by switching to a subscription model.
It is not that I don't trust you now. I just lost faith in promises like this.

Just switch to a cheap subscription model directly. (e.g. 1$ / Month, ...)

**Comment by KaKi87** [comment]
What about free for personal use ?

**Comment by lxnk** [comment]
@progmem64 
Dude, I have a very same experience, but a different point of view. Yes, I was angry about Tower, which I liked a lot and paid for v1 and v2. Then the subscription started and that was first time in my life when I was so sad that I shared this with the developers (usually I don't waste time for such drama crap)

But let's admit - if you write software - you are god-emperor of your realm. But you can't change past, only future. What I mean by that is following :
If developers sell "one-time purchase" - they sell you _this_ code. You wanna newer version? That is new code, pay for it. Tower did not break into your house and deleted all bought versions, right? They said next version will be sold under different conditions. You don't like them? Use older version. Or look for something else. What I, for example, did. If Tower wouldn't switch to subscription model, I would never use git-fork (not 'coz it's worse, but 'coz I was satisfied with what I had from Tower) So Dan can thank Tower for a number of customers who left Tower for git-fork. 

And yes, Dan can switch to 29.99$/supper, but most likely he will loose the freelance/personal_use customers (generally rather companies are ok with subscription model). 
But again, it's his decision, and you can keep what you bought.

////Lost another war in internets.

**Comment by c-alpha** [comment]
Agree with @lxnk that one-off-purchase does not enable a developer to keep improving and expanding his/her product forever. Call it a "paid upgrade", call it a "subscription"; at the end of the day, one needs an income to pay one's invoices month after month.

From an individual buyer's perspective, the one-off-purchase is what we are used to. From a business buyer's perspective, we are used to signing & paying for support contracts. Hence, as @lxnk points out, a business customer will be less reluctant to pay for a subscription. The freelancer (like my humble self) is a middle ground, probably. If it helps my work enough, I'm happy to churn out some money regularly. I know the guys making the tool are in the same situation as myself. That said, I'd be happy to pay a yearly fee. The 29.99 mentioned by @lxnk would be a very attractive offer, IMHO; but I would also deem up to 49.99 per year as "worth it".

**Comment by KaKi87** [comment]
So I've had time to think about it and I'm now coming back with this idea : how about making Fork free again for public git repositories and keeping it paid for private git repositories ?
This can be easily verified using `git ls-remote` : if it asks for authentication, then it's private.
100% cross-platform.
Thanks

**Comment by c-alpha** [comment]
Private repo usage is not necessarily linked to commercial use; at least for me.

**Comment by KaKi87** [comment]
I never said that.
However, public means open source, and private means proprietary.
Therefore, closed source, whether freeware, freemium or premium can stay paid.
Seems fair to me.

**Comment by c-alpha** [comment]
Make no mistake, I'd like to pay, too.

I use private repos for instance to kick-start new developments with a small team, which - when we think it's ready for th eyes of the public - are then launched as OSS projects. Linking pay to private repo hence seems to read too much into the fact that a repo is private, IMHO. That's all.

**Comment by KaKi87** [comment]
> Make no mistake, I'd like to pay, too.

Well, I don't, because I do 99.999% open source, and it feels unfair to me to pay premium software for open source purposes, that's why I'm trying to come up with a solution like this one.

> I use private repos for instance to kick-start new developments with a small team, which - when we think it's ready for th eyes of the public

In that case, you can just keep the repo public, only document `README.md` for developers but not for end users, make no releases, and if the project is a webapp, make no public URL.

**Comment by herrherrmann** [comment]
> [...] it feels unfair to me to pay premium software for open source purposes, that's why I'm trying to come up with a solution like this one.

@KaKi87 Please stop trying to come up with a solution here. The developers of this tool decided to turn their hobby project into a commercial one and very rightfully so. Please respect that decision. If you want to use a high-quality git UI client, then you can pay for Fork and use it. If you want to stick to open-source development, then feel free to use any of the available open-source (or otherwise unpaid) git clients. ✌️

**Comment by decuser** [comment]
I don't get all the whining. There aren't any stipulations on evaluating the software. Just evaluate it until you feel you want to pay for it. I used it for quite a while before I bought the license. I bought it because I liked the software and thought it was worth supporting. If it had been a 30 day license or somesuch, I would never have bought it.

**Comment by KaKi87** [comment]
> There aren't any stipulations on evaluating the software. Just evaluate it until you feel you want to pay for it.

Are you saying the evaluation period is actually unlimited ?

**Comment by alex-vas** [comment]
The evaluation is not unlimited.

As of now, you can evaluate the product until you confident that you want to buy it or confident that you are not going to buy it. At this point you should stop evaluation, and go ahead, buy or uninstall. The maximum evaluation period is not enforced as of now.

This is my understanding and it does not necessarily match or represent product owners position.

**Comment by KaKi87** [comment]
> The maximum evaluation period is not enforced

That's what I meant.
Well, I suppose I'm gonna download that "evaluation" version actually.
However, as soon as it becomes limited, if it doesn't get explicitly free for public repos, I'll have to uninstall again.

**Comment by gochev** [comment]
Does anyone knows what was the latest FREE version ? I have never updated but now I switched to a new PC and I am suddenly asked for evaluation. Also was it FOSS before ?

**Comment by svoop** [comment]
@gochev AFAIK it's never been FOSS. If reviewing the source code is important to you, there are plenty of other FOSS git clients available. However, if you like Fork for its distinct features and the responsiveness of the makers of Fork, how about supporting them by purchasing Fork?

**Comment by gochev** [comment]
@svoop actually no.. you can support them by donating, I am doing donations to manjaro, apache and other projects and foundations and I even said several times long time ago I would do a donation to FORK if there was a linux version (but there isn't still) , just to be clear  I have nothing against paid software, I have however issue with freeware software becoming paid, this is the actual reason why people should not use freeware software at all it is always a TRAP and I guess Fork is not different :)

**Comment by svoop** [comment]
@gochev Then you'd better go for one of the other git clients out there which are FOSS. Fork was free beta and is now unenforced paid release for quite some time – don't see any issue with that. I doubt there will be a Linux version.

**Comment by KaKi87** [comment]
@gochev As Dan said, the first freemium version of Fork was `1.0.86` (*https://github.com/ForkIssues/Tracker/issues/562#issuecomment-553339374*), so I guess the last freeware version was `1.0.85.2`. I found the Mac installer of this version [here](https://iusethis.luo.ma/fork/Fork-1.0.85.2.dmg) but not the Windows one unfortunately.

Anyway, the evaluation version doesn't have a duration limit yet, so I continue to use it for small projects while I'm now using the JetBrains IDE's native git integration for the bigger projects.

When that duration limit will come up though, I will stay at the previous version.

**Comment by Haprog** [comment]
I have an installer for Windows version of Fork 1.40.2.0 (the version numbers are different between Win and macOS, see https://fork.dev/releasenoteswin). This version was released in October 2019 (about a month before the license/pricing change was announced above). I had downloaded that just a bit before I changed to Linux as my main OS. I'm not sure what is the first Win version of Fork that has the license activation feature so.

I just tried installing this Fork 1.40.2.0 on a Win 10 machine and it doesn't seem to have the license thing, but after having the app open just a minute or two it automatically updated itself to latest version (and showed a notification about it). After restarting Fork it was on the latest version. And there doesn't seem to be any feature to turn off automatic updates. So you would need to block the network requests that Fork is using for auto-updates to be able to continue using an old version like this.

**Comment by Haprog** [comment]
I suspect Fork 1.41 for Win might still be without the license activation (assuming that the the feature landed first on macOS) and 1.42 probably has it already (since it was the first Win release after the macOS version of 1.0.86).

**Comment by KaKi87** [comment]
I'll look into it, thanks.

**Comment by svoop** [comment]
Funny how this issue morphed from "I do not understand how you are giving Fork away for free" to what hoops to jump to avoid the one-time price tag. :wink:

**Comment by KaKi87** [comment]
That's because the people who created and supported the issue have money and those who found it by accident doesn't.

**Comment by aonez** [comment]
@ForkIssues I suggest you don't delete comments (if they're not offensive), it's a bad idea to censure and better if your users talk here than in other places... Just my humble opinion. Maybe it's a better idea to lock the conversation if you don't want more fuss.

BTW I'm a happily licensed user but I understand some people (probably young) may have problems paying for software, not just Fork but any software. I was there before.

**Comment by DanPristupov** [comment]
I had to remove the **off-topic**, it really went too far. If somebody has a question or opinion about licensing or payment, please create a separate issue. I believe, the majority of people who left comments there do not want to receive a bunch of email notifications about searching an ancient Fork version.

**Comment by Stannieman** [comment]
Maybe the issue can just be closed. The issue was that it was free, now you can pay. Looks pretty resolved to me.

**Comment by c-alpha** [comment]
> Maybe the issue can just be closed. The issue was that it was free, now you can pay. Looks pretty resolved to me.

Couldn't agree more. Closing it would seem a wise thing to to do.

**Comment by avinash-synapsesai** [comment]
@DanPristupov would be like, `see guys I told you, that's why I wasn't keeping this paid, there is so much imbalance between users, some say they want free, some say they want to donate` just kidding 😂

Just keep up the good work! 👍

**Comment by spartanatreyu** [comment]
I would pay again for a linux version, just so I could ditch windows and WSL.

Happy 10th Birthday Fork!
