### ISSUE TITLE
When a file's permissions are changed, nothing is displayed in the diff

### ISSUE THREAD

**Issue by maksimovic** [fork-dev/Tracker#575]
Not sure if implementing this would add an overhead not being worth the hassle (and performance taking the hit?), but it may be confusing to see that there's a change - and simply nothing is visible in the diff ([screenshot](https://i.imgur.com/Rap5LCY.png)).

Seems that neither `git status` nor `git status -v` don't show such changes, only `git status -vv` does show those details:

```
| => git status -vv
On branch test-discard
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .travis.yml

--------------------------------------------------
Changes not staged for commit:
diff --git i/.travis.yml w/.travis.yml
old mode 100644
new mode 100755
no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by DanPristupov** [comment]
The main problem there is to find where to put that info,

**Comment by maksimovic** [comment]
Could it be a "bar" below the "true diff", saying something like `100644 -> 100755` if there's a change in permissons detected?

Github is showing it next to the filename, e.g.
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/1126226/54461251-5c2cf100-476c-11e9-9a1e-dabca11302d7.png">

 I've just downloaded SourceTree to check if it shows the permissions diff, and went through the stupid Bitbucket Cloud registraton (wow, can't use the app without it), just to discover that it doesn't really show anything, just like Fork. I was convinced that it does display it... time to win this battle :P

**Comment by stk-ableton** [comment]
First of all, I would also like to see this information, I think it is important.

git gui shows the information at the top of the main diff window:

<img width="1094" alt="Screenshot 2019-03-27 at 10 21 35" src="https://user-images.githubusercontent.com/7702697/55064509-63ac9e00-507a-11e9-9f38-92f85d2dfec8.png">

If there are also content changes, they will be displayed below that, like so:
<img width="1094" alt="Screenshot 2019-03-27 at 10 20 38" src="https://user-images.githubusercontent.com/7702697/55067927-e7698900-5080-11e9-8505-a5b7116bb35c.png">

I think this same layout could also work for Fork.

**Comment by DanPristupov** [comment]
I like the layout @maksimovic has proposed, but I need to check how it looks in RL.

**Comment by DanPristupov** [comment]
I forgot to mention that starting from 1.0.83 we show chmod change for text files.

**Comment by aonez** [comment]
> I forgot to mention that starting from 1.0.83 we show chmod change for text files.

@DanPristupov I'm not seeing that change. This will be interesting at least when there're no other changes than the permission ones. I'm sometimes not sure why I have a file to stage:

![Screenshot 2020-12-14 at 16 21 27](https://user-images.githubusercontent.com/480163/102099301-722b8200-3e28-11eb-843c-6cb1eef5a5b8.png)


Maybe adding a bar above the diff viewer in case of permission changes showing the change could do the trick, just giving ideas.

![Screenshot 2020-12-14 at 16 21 27](https://user-images.githubusercontent.com/480163/102100299-9176df00-3e29-11eb-8b2c-f0501292c7cc.png)
