### ISSUE TITLE
Can't finish Git Flow release branch

### ISSUE THREAD

**Issue by Jeehut** [fork-dev/Tracker#606]
We use git-flow but with different names (as git-flow explicitly supports). I just started a release branch named "deploy/3.0.0" but when I go to the Git-Flow menu, I **can't see or click a "finish" button.** 

Here's my `.git/config` file:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:Flinesoft/HandySwift.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "stable"]
	remote = origin
	merge = refs/heads/stable
[branch "productive"]
	remote = origin
	merge = refs/heads/productive
[gitflow "branch"]
	master = productive
	develop = stable
[gitflow "prefix"]
	feature = work/
	bugfix = bugfix/
	release = deploy/
	hotfix = hotfix/
	support = support/
	versiontag = 
[gitflow "path"]
	hooks = /Users/Name/Code/GitHub/Flinesoft/HandySwift/.git/hooks
[gitflow "branch.work/test"]
	base = stable
[gitflow "branch.work/sdm"]
	base = stable
[gitflow "branch.work/withable"]
	base = stable
[gitflow "branch.deploy/3.0.0"]
	base = stable
```

I'm using Fork 1.0.77. Would be great if this got fixed! (Or did I oversee something?)

**Comment by DanPristupov** [comment]
The item should be in the context menu.
Right click on the commit (or branch on the sidebar) -> Finish git flow feature.

**Comment by Dschee** [comment]
Ah, I see it now. Thanks! But that's quite impractical, to be honest. I'm trying to switch to Fork at the moment from SourceTree (and might recommend it in my company), and in SourceTree, when you click on the "Git-Flow" button, it detects that I'm currently in a release branch (deploy in our case) and also shows a "Finish" button there. Would be great if this could be added here as well! 👍 

Also, since this software is free, did you ever consider making it (or most parts of it) open source? That way, I could add such features myself and it would be less work for you.

**Comment by DanPristupov** [comment]
But there's no Git-Flow button in Fork.

Open sourcing is not in our plans for the near future.

**Comment by Dschee** [comment]
I do think that Fork has a Git-Flow button, even if you don't call it that, but effectively this

<img width="191" alt="Bildschirmfoto 2019-04-30 um 18 03 33" src="https://user-images.githubusercontent.com/6942160/56976124-8434b000-6b72-11e9-9715-a45bffa5f20c.png">

has everything that I would compare it to the "Git-Flow" button in SourceTree. Also there's this place in the menu, where I would expect the same behavior:

<img width="392" alt="Bildschirmfoto 2019-04-30 um 18 04 09" src="https://user-images.githubusercontent.com/6942160/56976178-a4fd0580-6b72-11e9-8609-da83a46a34ed.png">

Okay, fair enough. Thank you for providing this great tool anyways!
