### ISSUE TITLE
[Feature request] Ability to filter branches in the graph

### ISSUE THREAD

**Issue by mskonovalov** [fork-dev/Tracker#614]
Currently there are too many branches so the tree looks almost unusable.
I'd prefer to be able to do some filtering like you can do in Intellij Idea

e.g. set the filter:
```
origin/master|master|username/*|origin|username/*
```
Otherwise currently the distance between commits in your branch and last commits in base branch might be several screens

**Comment by yinheli** [comment]
We need this feature tool!

**Comment by DanPristupov** [comment]
So, you basically want to be able to filter folders, right?

There's already an issue for that https://github.com/ForkIssues/Tracker/issues/382

**Comment by yinheli** [comment]
Not the same. We need filter log, to limit the commit view (graph), to prevent situation like following: 😂
![image](https://user-images.githubusercontent.com/235094/59841093-38d69b00-9386-11e9-914f-b35257ee75b7.png)

**Comment by DanPristupov** [comment]
Not sure how this is related to the original post.

How you would like to improve that? I don't see any branch there.

**Comment by mskonovalov** [comment]
Yes, I think the screen is a bit irrelevant as it will not filter out commits that were merged.
But we use in our repo 'squash and merge' approach which makes master linear.
So filtering will be helpful for our case for sure.

**Comment by DanPristupov** [comment]
@mskonovalov do you use the branch filter already?

<img width="441" alt="image" src="https://user-images.githubusercontent.com/618115/59848079-93f79600-9364-11e9-9f64-0fb0980ac5eb.png">

**Comment by mskonovalov** [comment]
yep, but I want to have several branches: e.g. all my local + all my remote + local master + remote master

**Comment by mskonovalov** [comment]
there might be several scenarios depending on the branching model used

**Comment by mskonovalov** [comment]
oh, wait, I didn't notice you can select several branches
but the selection mechanism is not ideal - when you scroll over the branch list and selec one of the branches it jumps back to the top of the list.

So instead I'd say this task should sound like "Provide ability to write filter"
so that the current filter
<img width="572" alt="image" src="https://user-images.githubusercontent.com/4463812/59850405-874b6000-93ad-11e9-9633-e25bed289c4f.png">
can be edited in text format in addition to clicks

**Comment by yam-liu** [comment]
I second this. 
Our CI will create many PR-based shadow branch to do pre-compile, these branch will show in history view. This makes the tree view be messy and loss focus to what we really care.
So can we have a function that omit some branch (use regex or simple string prefixes suffixes) from history view?

![image](https://user-images.githubusercontent.com/1056803/93194274-7e953580-f77a-11ea-92dd-d7a926bd50ea.png)

**Comment by DanPristupov** [comment]
@ooopscc You can set filter on any branch and omit the branches which are not merged into it (or press Cmd+Shift+A to quickly set filter on the active branch).

**Comment by yam-liu** [comment]
@DanPristupov 

This filters active branches, but not my need. 
Specifically, CI branch names have prefix in common, such as `origin/ci/patch_mr_auto_`. 
These were created as shadow branches that merge feature branch changes to it and compile to see if any errors, we care about the errors but these branches/commits make no sense for we developers. 
So, I want to show all history but not these branches.

**Comment by DanPristupov** [comment]
In Fork 2.6 you can set filter on folders
