### ISSUE TITLE
Tabs are lost when closing fork

### ISSUE THREAD

**Issue by jopenmolles** [fork-dev/Tracker#622]
Using Fork 1.0.78.2 on MacOS 10.14.4 I have the issue that when I close fork (press the red button) and I reopen it, all tabs are closed. When I quit fork using Cmd+Q, the tabs are kept. 

Is this intended behaviour and/or is there perhaps an option to keep the tabs when closing fork using the red button?

**Comment by DanPristupov** [comment]
This is how all applications in macOS work, isn't it?
Close Safari with `x` button -> tabs are lost
Close Safari with Cmd+Q -> tabs are kept

**Comment by jopenmolles** [comment]
I'm coming from Windows so, I'm not very familiar yet with MacOS's behaviour, but I like the behaviour of the Windows version of Fork more. To me it seems that it depends on the program whether tabs are kept or lost:
-  Chrome, Safari and Photoshop lose all tabs for me when pressing either the `x` button or Cmd+Q.
- Visual Studio Code and Sublime merge for example work as you described.
- Intellij, Visual Studio and Thunderbird keep the tabs when using the `x` button and Cmd+Q.

I have the option `Close windows when quitting an app` turned on under `System Preferences -> General`, but turning it off did not matter for Fork's behaviour.

**Comment by DanPristupov** [comment]
This issue can be related: https://github.com/ForkIssues/Tracker/issues/277

> I have the option Close windows when quitting an app turned on under System Preferences -> General, but turning it off did not matter for Fork's behaviour.

That's true. Fork overrides that option because in recent versions of macOS it became `false` by default. Users got confused that Fork doesn't restore session.

**Comment by noheger** [comment]
I’m usually working with lots of open tabs and I also find it quite annoying to lose all my tabs when I accidentally close the window.

Yes, Safari also closes all tabs when you close a window, but to address the issue of closing a window by accident, there’s a “Reopen Last Closed Window” command in Safari’s “History” menu.

You might also offer such a command. Or, alternatively, show at least a dialog when closing a window with multiple tabs, asking: “Do you really want to close this window? All your open tabs will be closed.”

**Comment by DanPristupov** [comment]
I'll try to check if it's possible to force document to be saved on close when only one window exists (same as in Finder, I think).

It's all very annoying though :(. I already received an (unofficial) warning from an Apple employee because Fork saves session even if `Close windows when quitting an app` system settings is off. Apple does want us to struggle.

Looking for a hack to always save the session will bring another bunch a problems.

**Comment by rventurelli** [comment]
A possible solution can be implement the feature #641  (also in Windows please... :-))

**Comment by pwnified** [comment]
I found a workaround. If you accidentally close the window and all your carefully handplaced tabs disappear, instead of headbutting the monitor again, quickly go to the Apple menu and force close Fork. Now when starting Fork again, your tabs will be back.

**Comment by DanPristupov** [comment]
Starting 2.27 Fork manages application windows manually and restores tabs on close.
