### ISSUE TITLE
[feature request] open repository in web browser

### ISSUE THREAD

**Issue by StefanoCecere** [fork-dev/Tracker#628]
i miss the command to open the current repo online in a web browser (at its url https://github.com/ForkIssues/Tracker/ for example)

the command could be in the Repository menu, or in the Remotes list (with contextual menu)

what do you think?

**Comment by DanPristupov** [comment]
<img width="255" alt="image" src="https://user-images.githubusercontent.com/618115/58156618-c8e5cf80-7c76-11e9-8f48-23d47e1144e5.png">

We need to make it more clear though.

**Comment by StefanoCecere** [comment]
ah well.. yes, absolutely :)

**Comment by StefanoCecere** [comment]
maybe even jsut adding these menus to the File main menu (like most app do: the export/open in commands are both by this icon and in the file menu

**Comment by laurentvaills** [comment]
I am using Fork not with a cloud hosted git server but a self hosted git server (Atlassian Bitbucket v5.8.0) and unfortunately I do not have this "View on..." which could be quite useful.

**Comment by DanPristupov** [comment]
Is there a way the website url can be recognized in your remote git server address?

**Comment by laurentvaills** [comment]
Here the info for my remote `upstream` :
```
Fetch URL: ssh://git@git-server.example.com:7999/project-name/repo-name.git
```

The website URL is : https://git-server.example.com/projects/project-name/repos/repo-name/browse .
