### ISSUE TITLE
Turn off smart quotes/smart dashes in commit text fields

### ISSUE THREAD

**Issue by stk-ableton** [fork-dev/Tracker#634]
I'm aware that git works fine when there are curly quotes or other non-ASCII characters in commit messages; however, I'd still like to avoid them to avoid problems for command-line users who haven't configured their terminals correctly.

By default, smart quotes and smart dashes are turned on in Fork's commit message window; I'd like these to be off. I know I can turn them off globally in System Preferences, but I do find them useful in other text fields, just not in Fork's.

<img width="528" alt="Screenshot 2019-05-28 at 11 49 58" src="https://user-images.githubusercontent.com/7702697/58469368-a30d6e80-813f-11e9-9f95-30ec0a2c3f80.png">

**Comment by 153957** [comment]
They are not turned on by default in Fork's inputs, they follow your system settings. So I think it is up to you to choose to enable or disable them by default in all normal input fields (via the system preferences).

**Comment by DanPristupov** [comment]
@153957 yes, they follow the system settings. However I agree with @stk-ableton, these 2 'smart modifications' might be good in some areas, but not for commit message which quite often must be strictly tailored and precise.

**Comment by 153957** [comment]
Personally I would suggest that if you sometimes need smart quotes that you just use the correct key combo to write them (i.e. option + `[` or `]` or `-`) and not let the system determine when you need it, so just disable them by default, but that is just my opinion.

**Comment by stk-ableton** [comment]
Thank you for fixing this!

Personally I think you went one step too far with the fix though: it seems you also disabled Smart Copy&Paste, which I think is actually very useful when editing commit messages. It might make sense to disable this in a code editor, but commit messages are plain language, so cutting and pasting whole words should be "smart".

It's not a huge deal for me though, so if you decide to keep it this way for some reason, I can live with it.

**Comment by DanPristupov** [comment]
Fixed in 1.0.79

**Comment by stk-ableton** [comment]
> Fixed in 1.0.79

Thanks for that! Any thoughts about the Smart Copy&Paste though? (See my previous comment.)

**Comment by DanPristupov** [comment]
I missed that. Will add in the next update, which is planned for the next week.

**Comment by DanPristupov** [comment]
1.0.80 is out.
I enabled 'smart copy and paste' and disabled 'automatic spell correction' because it automatically capitalized first word (the usual spellchecking still works).

**Comment by stk-ableton** [comment]
Awesome, thanks!

Now the last little request is that the same settings should also apply to the Reword dialog in an interactive rebase.

**Comment by DanPristupov** [comment]
:)
