### ISSUE TITLE
[Feature Request] Include a way to view tag messages

### ISSUE THREAD

**Issue by vewert** [fork-dev/Tracker#636]
When creating a Tag, you can include an optional message. It would be nice to have some way to view the message later on. This could be done by having a right-click properties on the Tag (which would include the message), or maybe as a Tooltip, by mousing over the Tag, or both.

**Comment by Drarok** [comment]
Took me a while to find this issue since I was looking for annotated / annotation etc. +1 for this feature, spent a while looking for it given you can _create_ annotated tags, but I can't find it.

**Comment by r-owen** [comment]
This is, so far, my biggest issue with Fork. Tag annotations are often important, and an easy way to view them would be really helpful. (SourceTree does make the information available, though it's a bit clumsy; I hope Fork can make it easier).

**Comment by vewert** [comment]
Just an FYI, I have noticed that this seems to have been implemented on Fork for Windows, but not yet on macOS.

Hovering your mouse over a Tag (in the left panel), gives a Tooltip with the Tag name, date it was created and the message/annotation.

I hope this helps.

**Comment by r-owen** [comment]
On macOS if I hover the mouse over a tag in the left column (under Tags) I get the date but not the annotation. In any case I would strongly prefer that the annotation be presented in a way that can be copied (e.g. so I can use it in release notes).
