### ISSUE TITLE
[Feature Request] Save/Load All Open Tabs (Repos)

### ISSUE THREAD

**Issue by vassilevsky** [fork-dev/Tracker#641]
Hello ☺️

I have a small fear of losing my Fork "session" — the set of open tabs with repositories in them.

I usually have tabs for all repositories that I maintain. This set varies over time, slightly. I have around 20 tabs open.

Fork usually remembers them. When I turn my computer off, and then on again, it opens all tabs again, which is great. But I have a fear that I will lose this "memory" and will have to open all repos again. This has happened before for reasons I don't understand and that makes me slightly nervous. Silly, I know.

Can I have a "Save tabs" menu command or something like that?

I have to say that this is the only issue I have with Fork right now. It's excellent in all other regards. Fantastic job!

Thank you!

**Comment by DanPristupov** [comment]
This is tricky, because active sessions are managed automatically by macOS. When I have some free time, I will try to find an ability to customize that.

**Comment by rventurelli** [comment]
This will be a great feature.
Open a group of projects previously saved.
And for each group made some custom features like fetch/pull all projects automatically when group is open.

**Comment by pwnified** [comment]
I've done this several times... had lots of tabs configured exactly the how I wanted them, then a single misplaced click on the window close button and they are gone. Other apps that support tabs (say, Firefox) will close the program down and save the tabs. But Fork just deletes all your tabs and the program remains running. Please fix this.

**Comment by grumpygamer** [comment]
+1 for this feature. One misclick and I've lost all my tabs.  I have 5 opens tabs all day long.
