### ISSUE TITLE
Interactive rebase: add discard (soft reset) last commit option

### ISSUE THREAD

**Issue by rolandleth** [fork-dev/Tracker#652]
Hello!

When rebasing interactively to edit a commit, it would be nice to also discard (soft reset) that commit's changes, to more easily see what changes actually happened there.

Manually calling `git reset @~` does the trick, but it would be nice to be able to do it automatically. Preserving the commit's message would also be super nice, since the command doesn't do that 😞

Thank you!

**Comment by DanPristupov** [comment]
I think we should not alter the IR behavior to not confuse users who use it for years.

However I think it would be nice to set `amend` checkbox automatically (which basically does the same - shows the changes in the commit).

**Comment by rolandleth** [comment]
I didn't even realize that would also do the trick and in a better fashion than my suggestion!

Furthermore, aborting the rebase should untick the `amend` checkbox automatically as well, as to not remain with pending changes that make no sense.
