### ISSUE TITLE
[Feature] Propose to create a pull request after push

### ISSUE THREAD

**Issue by ByScripts** [fork-dev/Tracker#659]
When using `git push` in the console to push my branch to Bitbucket, the output gives me a direct link to create a pull request.

When using Atlassian Sourcetree, there is an option "Create pull request" in the commit panel, which open the Bitbucket webpage.

Could be great to have an option in Fork for this, for example:
- Having a "Create pull request" checkbox next to the "Amend" checkbox
or
- After a push, ask the using "Do you want to create a pull request ? [Yes] [No]"

I find it boring, after a commit/push, going to Remotes, searching for my remote branch which has been created, right clicking on it, selecting "Create pull request on Bitbucket.org...".

Thank you :)

**Comment by DanPristupov** [comment]
> When using git push in the console to push my branch to Bitbucket, the output gives me a direct link to create a pull request.

You can open push output in the activity manager on the toolbar and see that link.
