### ISSUE TITLE
[Feature request] Integrate "Changes" View also in "All commits"

### ISSUE THREAD

**Issue by fkoehler** [fork-dev/Tracker#660]
This is the way sourcetree does it and the benefit is that within one window one can see the entire history and directly see the changes files and be ready to stage them. See the following screenshot:

![image](https://user-images.githubusercontent.com/943818/59838335-0c535c80-934f-11e9-922c-51b2bfdee23e.png)

**Comment by fkoehler** [comment]
I think it could similar to how you display stashes in the "All commits". I really like that you see the stash put on top of a commit where it came from. Similar to that you could show the "Changes" on top of the current HEAD like a commit with it's changes. This would avoid switching between the two views and have everything integrated in one view

**Comment by sneko** [comment]
+1

@DanPristupov that's also used in GitKraken 😃

**Comment by dndrsn** [comment]
This is the only feature I miss from SourceTree

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/Tracker/issues/308

**Comment by marcoreni** [comment]
@DanPristupov it's unclear to me if this has been released or not. The link you provided is a self link and I'm unable to see this inside Fork.

**Comment by DanPristupov** [comment]
I made a typo. This is a duplicate of https://github.com/fork-dev/Tracker/issues/308
