### ISSUE TITLE
[Bug] Cannot stage chunks or lines in files that are in folders with special characters

### ISSUE THREAD

**Issue by DOFandersolsen** [fork-dev/Tracker#663]
Hi,

I'm currently experiencing the same problem on the Mac-version of Fork as I am on the Windows version.

I have created the Windows issue here: https://github.com/ForkIssues/TrackerWin/issues/330

I have a file: `observatør/index.html`
The file is already in Git, but I've made changes and I want to stage only some of the changes for my next commit.

I mark the lines and press Stage, but nothing happens.
I also try to stage one of the chunks, but again nothing happens.

However, I can stage the entire file and it'll be added to Staged Changes.

**Comment by DanPristupov** [comment]
I think this issue has already been resolved.
