### ISSUE TITLE
Contextual menu load time

### ISSUE THREAD

**Issue by tflo** [fork-dev/Tracker#676]
Often when I right-click a file, it takes a considerable time for the contextual menu to open, because it waits until any external disks have spun up.

I guess, this is caused by the Open With menu item and its applications submenu that has to be built from scratch.

![Screen Shot 2019-07-08 at 13 24 20 copy-pty](https://user-images.githubusercontent.com/1410282/60866633-259e4900-a229-11e9-8fa8-a3b82891e4e3.png)

We know this from other apps, like the Finder, but the difference is that in the Finder the contextual menu opens immediately, and *only when I select the Open With menu item* I see the disk spin-up and have to wait until the submenu is populated.

In Fork this delay occurs already when I try to open the contextual menu (not only when I select the Open With menu item). 

This can be a bit annoying, and I think there might be a way to make it behave more like the Finder’s (or other apps’) contextual menu (not fetching applications until Open With is selected).

Thanks for considering (or please let me know if my assumptions are wrong)

– Tom

**Comment by DanPristupov** [comment]
This is an interesting observation. I will investigate that.

**Comment by DanPristupov** [comment]
Does that problem still bother you?

**Comment by tflo** [comment]
I seem to have missed your reply from 2023, sorry. Thanks for asking.

I haven't seen this problem for a while now, I even forgot I had this problem once. That means it was fixed, or fixed itself, somewhere in the first few years after I posted this ;)  I also moved to a new iMac in late July 2019, so maybe it was hardware related…
