### ISSUE TITLE
Duplicated avatar after commit

### ISSUE THREAD

**Issue by enricobenedos** [fork-dev/Tracker#678]
I'm starting using Fork instead of SourceTree. At the moment I'm using both the clients. But after the commits made with Fork, it happens that on SourceTree in the commit details I found two avatar. This isn't a problem but it is a very strange behavior. 
Here an example of a commit made with Fork:
![image](https://user-images.githubusercontent.com/12233746/61060244-8a5ccd80-a3fa-11e9-9ed7-97a3dc136bd2.png)
As you can see the avatar is duplicated. Normally there is only one avatar as expected.

**Comment by DanPristupov** [comment]
I can't really tell you how SourceTree works, but I guess it might show you Author and Committer when they are different. This might happen after amend/rebase, for example.

**Comment by enricobenedos** [comment]
You cannot se that but in my case the avatar is the same. In my case author and committer are always me. In the example it was only a simply commit on develop branch. There are no problems basically, I was just looking for an explanation about this particular behavior that I cannot see before. Thank you for your interest about it. If you want we can close this “issue”

**Comment by DanPristupov** [comment]
Author info consists of author username, author email and author date. When you amend/rebase author date and committer date differ.

I suppose simple commit will not have a duplicated avatar. Amending it will make the committer info (and avatar) visible.

**Comment by enricobenedos** [comment]
This how I normally commit on Fork:
![image](https://user-images.githubusercontent.com/12233746/61114574-e3774080-a490-11e9-9378-a55df424e994.png)
I don't use amend/rebase

**Comment by DanPristupov** [comment]
No, there's no settings for that.

* Does Fork show 2 avatars as well?
* Are the author and committer dates different for the commit with 2 avatars?

**Comment by enricobenedos** [comment]
> No, there's no settings for that.
> 
> Does Fork show 2 avatars as well?
> Are the author and committer dates different for the commit with 2 avatars?

> No, Fork shows only one avatar 
> Author and committer is the same, in this case me, and the date is only one. There is a specific location where I can find this information?

**Comment by DanPristupov** [comment]
You can see that info this way:

`git log --pretty=format:'%h %an %ae %ad %cn %ce %cd %s'`

Regarding the original question, it looks like you should ask the ST support team about that.

**Comment by enricobenedos** [comment]
Thank you for the git command. It helps me to see the difference between ST and Fork commit:
```
Fork commit: 8c51189 author: name.surname@mail.com name.surname@mail.com Thu Jul 11 16:31:32 2019 +0200 committer: name.surname@mail.com name.surname@mail.com Thu Jul 11 16:31:32 2019 +0200 Removed FrozenColumnsSplitterVisibility on change language window
ST commit: e6e0c15 author: Name Surname name.surname@mail.com Thu Jul 11 10:09:21 2019 +0200 committer: Name Surname name.surname@mail.com Thu Jul 11 10:09:21 2019 +0200 Fixed an error in the changelog
```
The difference is that ST identify the author with this pattern:
`NAME SURNAME name.surname@mail.com`
Fork:
`name.surname@mail.com name.surname@mail.com`

Is it an exptected behavior by Fork? Because in the GIT settings I correctly input the username and email information:
![image](https://user-images.githubusercontent.com/12233746/61205472-6e09ab00-a6f0-11e9-8c43-33a87b16d08b.png)

GIT internally use this template to store the commit informations:
```
author {author_name} <{author_email}> {author_date_seconds} {author_date_timezone}
committer {committer_name} <{committer_email}> {committer_date_seconds} {committer_date_timezone}
```
It seems like Fork doesn't use the given username when a user commit. It seems that it use only the email information
