### ISSUE TITLE
[Feature Request] Show commits from current branch only

### ISSUE THREAD

**Issue by clounie** [fork-dev/Tracker#85]
When the git history gets complicated with a dozen+ branches in the tree, it's often hard to keep track of commits that were made specifically to your branch.

**Suggestion:** Add a dot to the left of the commit timestamp for all commits that are in your particular branch.

![example-dots](https://user-images.githubusercontent.com/11947182/29729353-07321bd6-8999-11e7-815c-1fd4a511820a.png)

It'd honestly be nice to have a switch which limits the git tree to *only* display commits from the current branch. But the dot thing would probably be easier, and accomplish the same thing.

**Comment by DanPristupov** [comment]
Hi @clounie. May be you missed that, but commits which belong to the active branch are black, and the ones which don't are gray. Isn't this the feature you're asking for?

<img width="1145" alt="2017-08-25 at 23 14" src="https://user-images.githubusercontent.com/618115/29732951-4c3bed18-89eb-11e7-855a-cba84d3a7068.png">

**Comment by clounie** [comment]
Nope, didn't miss it - mine doesn't do that. For ex:

![image](https://user-images.githubusercontent.com/11947182/29734626-879182e6-89b0-11e7-8c1b-189e26228cc9.png)

Here's my setup:
![image](https://user-images.githubusercontent.com/11947182/29734659-b9151184-89b0-11e7-8f63-acc2d5befda7.png)

**Comment by clounie** [comment]
I don't think so. 

**Use Case:**
Sometime in the last two weeks, I broke a component in our code. I know that it was in my branch - and thus want to see only commits that were made to my branch **explicitly**.

The environment might be like so:
1. We have, say, a `dev` branch and 5 feature branches
2. Everyone else merges their branches into dev
3. I pull the latest from dev into my branch

At this point, pretty much every single commit from every branch will be black - rendering the grey/black difference useless.

So. My request is that given this view:

![image](https://user-images.githubusercontent.com/11947182/29734866-f9db16c2-89b1-11e7-8500-c68648d23859.png)

..I want to be able to narrow it to **only** see the commits which have dots in the first branch's column. (in this case - two)

**Comment by DanPristupov** [comment]
I see what you mean. You want to see the commits, which belong to your current branch subtree and don't belong to any other one. We also must differentiate local and remote branches.

This seems to be tricky to implement. I need to figure...

**Comment by SusanRatiLane** [comment]
I have just started using Fork, and I'm really impressed. But I was just searching for a way to do this exact thing. We have a large project, and the history view gets incredibly cluttered.

**Comment by clounie** [comment]
@SusanRatiLane Dan added this a while back - I just forgot this issue was open.

You can click the "Filter" icon beside a branch's name to only see commits that are in that branch.

![image](https://user-images.githubusercontent.com/11947182/179265406-b4bb17e8-8a2b-4e4c-92b4-dc4f8a171c4e.png)

**Comment by SusanRatiLane** [comment]
Oh wow, thank you. I had been trying to mark everything invisible that I didn't want to see, and that wasn't sufficient. Thanks for the guidance on the filter icon.

**Comment by ChrisHoopes** [comment]
Just wanted to shoutout this feature, I had no idea those icons did that! Thanks!
